Logical: HNPainEvaluationsModel
Id: HNPainEvaluationsModel
Title: "居家護理－疼痛評估邏輯模型"
Description: "描述居家護理疼痛評估的資料需求。依 V5.0.16 有效欄位建立，來源欄位對應另列於 Mapping。"
* ^status = #draft
* ^version = "5.0.16"
* date 1..1 date "紀錄日期" "紀錄日期"
* nurseID 1..1 string "護理人員身分證字號" "護理人員身分證字號"
* statement 0..1 string "無法評估原因或備註" "無法評估原因或備註"
* scale 1..1 Coding "言語狀態" "言語狀態"
* scale from hn-vs-a370027f399e (required)
* questions 0..1 BackboneElement "評估項目" "評估項目"
* questions.qc6065ee9 0..1 BackboneElement "部位" "部位"
* questions.qc6065ee9.answer 1..1 string "評估答案" "評估答案"
* questions.qabb84b45 0..1 BackboneElement "分數" "分數"
* questions.qabb84b45.answer 1..1 string "評估答案" "評估答案"
* questions.q09558b2c 0..1 BackboneElement "時間" "時間"
* questions.q09558b2c.answer 1..1 string "評估答案" "評估答案"
* questions.q62ecf378 0..1 BackboneElement "性質" "性質"
* questions.q62ecf378.answer 1..1 string "評估答案" "評估答案"
* questions.q3ae9ab7d 0..1 BackboneElement "備註" "備註"
* questions.q3ae9ab7d.answer 1..1 string "評估答案" "評估答案"
* questionsNot 0..1 BackboneElement "無法言語評估項目" "無法言語評估項目"
* questionsNot.qd14007fb 0..1 BackboneElement "呼吸型態" "呼吸型態"
* questionsNot.qd14007fb.answer 1..1 string "評估答案" "評估答案"
* questionsNot.qe42750dd 0..1 BackboneElement "不舒服、負向情緒的發聲" "不舒服、負向情緒的發聲"
* questionsNot.qe42750dd.answer 1..1 string "評估答案" "評估答案"
* questionsNot.q3e683be4 0..1 BackboneElement "臉部表情" "臉部表情"
* questionsNot.q3e683be4.answer 1..1 string "評估答案" "評估答案"
* questionsNot.q463fccdc 0..1 BackboneElement "肢體語言" "肢體語言"
* questionsNot.q463fccdc.answer 1..1 string "評估答案" "評估答案"
* questionsNot.q9f3bcfc5 0..1 BackboneElement "可安撫程度" "可安撫程度"
* questionsNot.q9f3bcfc5.answer 1..1 string "評估答案" "評估答案"
* isTemporary 0..1 Coding "是否暫存" "是否暫存"
* isTemporary from hn-vs-58e4d598f859 (required)

Mapping: HNPainEvaluationsModelToFHIR
Id: hn-painevaluations-fhir
Title: "居家護理－疼痛評估欄位對應"
Source: HNPainEvaluationsModel
Target: "http://ltc-ig.fhir.tw/StructureDefinition/HNPainEvaluationsResponse"
* date -> "QuestionnaireResponse.item.where(linkId='Date')" "來源欄位／題目：Date"
* nurseID -> "QuestionnaireResponse.item.where(linkId='NurseID')" "來源欄位／題目：NurseID"
* statement -> "QuestionnaireResponse.item.where(linkId='Statement')" "來源欄位／題目：Statement"
* scale -> "QuestionnaireResponse.item.where(linkId='Scale')" "來源欄位／題目：Scale"
* questions -> "QuestionnaireResponse.item.where(linkId='Questions')" "來源欄位／題目：Questions"
* questions.qc6065ee9 -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qc6065ee9')" "來源欄位／題目：Questions[Question='部位']"
* questions.qc6065ee9.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qc6065ee9').item.where(linkId='Questions.qc6065ee9.Answer')" "來源欄位／題目：Questions[Question='部位'].Answer"
* questions.qabb84b45 -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qabb84b45')" "來源欄位／題目：Questions[Question='分數']"
* questions.qabb84b45.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qabb84b45').item.where(linkId='Questions.qabb84b45.Answer')" "來源欄位／題目：Questions[Question='分數'].Answer"
* questions.q09558b2c -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q09558b2c')" "來源欄位／題目：Questions[Question='時間']"
* questions.q09558b2c.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q09558b2c').item.where(linkId='Questions.q09558b2c.Answer')" "來源欄位／題目：Questions[Question='時間'].Answer"
* questions.q62ecf378 -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q62ecf378')" "來源欄位／題目：Questions[Question='性質']"
* questions.q62ecf378.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q62ecf378').item.where(linkId='Questions.q62ecf378.Answer')" "來源欄位／題目：Questions[Question='性質'].Answer"
* questions.q3ae9ab7d -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q3ae9ab7d')" "來源欄位／題目：Questions[Question='備註']"
* questions.q3ae9ab7d.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q3ae9ab7d').item.where(linkId='Questions.q3ae9ab7d.Answer')" "來源欄位／題目：Questions[Question='備註'].Answer"
* questionsNot -> "QuestionnaireResponse.item.where(linkId='QuestionsNot')" "來源欄位／題目：QuestionsNot"
* questionsNot.qd14007fb -> "QuestionnaireResponse.item.where(linkId='QuestionsNot').item.where(linkId='QuestionsNot.qd14007fb')" "來源欄位／題目：QuestionsNot[Question='呼吸型態']"
* questionsNot.qd14007fb.answer -> "QuestionnaireResponse.item.where(linkId='QuestionsNot').item.where(linkId='QuestionsNot.qd14007fb').item.where(linkId='QuestionsNot.qd14007fb.Answer')" "來源欄位／題目：QuestionsNot[Question='呼吸型態'].Answer"
* questionsNot.qe42750dd -> "QuestionnaireResponse.item.where(linkId='QuestionsNot').item.where(linkId='QuestionsNot.qe42750dd')" "來源欄位／題目：QuestionsNot[Question='不舒服、負向情緒的發聲']"
* questionsNot.qe42750dd.answer -> "QuestionnaireResponse.item.where(linkId='QuestionsNot').item.where(linkId='QuestionsNot.qe42750dd').item.where(linkId='QuestionsNot.qe42750dd.Answer')" "來源欄位／題目：QuestionsNot[Question='不舒服、負向情緒的發聲'].Answer"
* questionsNot.q3e683be4 -> "QuestionnaireResponse.item.where(linkId='QuestionsNot').item.where(linkId='QuestionsNot.q3e683be4')" "來源欄位／題目：QuestionsNot[Question='臉部表情']"
* questionsNot.q3e683be4.answer -> "QuestionnaireResponse.item.where(linkId='QuestionsNot').item.where(linkId='QuestionsNot.q3e683be4').item.where(linkId='QuestionsNot.q3e683be4.Answer')" "來源欄位／題目：QuestionsNot[Question='臉部表情'].Answer"
* questionsNot.q463fccdc -> "QuestionnaireResponse.item.where(linkId='QuestionsNot').item.where(linkId='QuestionsNot.q463fccdc')" "來源欄位／題目：QuestionsNot[Question='肢體語言']"
* questionsNot.q463fccdc.answer -> "QuestionnaireResponse.item.where(linkId='QuestionsNot').item.where(linkId='QuestionsNot.q463fccdc').item.where(linkId='QuestionsNot.q463fccdc.Answer')" "來源欄位／題目：QuestionsNot[Question='肢體語言'].Answer"
* questionsNot.q9f3bcfc5 -> "QuestionnaireResponse.item.where(linkId='QuestionsNot').item.where(linkId='QuestionsNot.q9f3bcfc5')" "來源欄位／題目：QuestionsNot[Question='可安撫程度']"
* questionsNot.q9f3bcfc5.answer -> "QuestionnaireResponse.item.where(linkId='QuestionsNot').item.where(linkId='QuestionsNot.q9f3bcfc5').item.where(linkId='QuestionsNot.q9f3bcfc5.Answer')" "來源欄位／題目：QuestionsNot[Question='可安撫程度'].Answer"
* isTemporary -> "QuestionnaireResponse.item.where(linkId='IsTemporary')" "來源欄位／題目：IsTemporary"
