Logical: HNBaseDataModel
Id: HNBaseDataModel
Title: "居家護理－個案基本資料邏輯模型"
Description: "描述居家護理個案基本資料的資料需求。依 V5.0.16 有效欄位建立，來源欄位對應另列於 Mapping。"
* ^status = #draft
* ^version = "5.0.16"
* caseID 1..1 string "個案身分證字號" "個案身分證字號"
* endDate 1..1 date "收案日期" "收案日期"
* caseSource 1..1 BackboneElement "收案來源" "收案來源"
* caseSource.value 1..1 Coding "選項" "選項"
* caseSource.value from hn-vs-ef3233b113ad (required)
* caseSource.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* caseName 1..1 string "個案姓名" "個案姓名"
* sex 1..1 BackboneElement "性別" "性別"
* sex.value 1..1 Coding "選項" "選項"
* sex.value from hn-vs-c8f650cb37b1 (required)
* sex.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* caseType 1..1 Coding "個案類型" "個案類型"
* caseType from hn-vs-082869c8d896 (required)
* birthdate 1..1 date "出生日期" "出生日期"
* phoneNumber 1..1 string "聯絡電話" "聯絡電話"
* address 1..1 BackboneElement "居住地址" "居住地址"
* address.city 1..1 string "縣市" "縣市"
* address.area 1..1 string "鄉鎮市區" "鄉鎮市區"
* address.lane 1..1 string "街路門牌" "街路門牌"
* education 1..1 BackboneElement "教育程度" "教育程度"
* education.value 1..1 Coding "選項" "選項"
* education.value from hn-vs-8bcd09f153b7 (required)
* education.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* marriage 1..1 BackboneElement "婚姻狀況" "婚姻狀況"
* marriage.value 1..1 Coding "選項" "選項"
* marriage.value from hn-vs-924b837448d2 (required)
* marriage.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* religion 1..1 BackboneElement "宗教信仰" "宗教信仰"
* religion.value 1..1 Coding "選項" "選項"
* religion.value from hn-vs-f6130a2de850 (required)
* religion.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* exJob 1..1 BackboneElement "主要職業" "主要職業"
* exJob.value 1..1 Coding "選項" "選項"
* exJob.value from hn-vs-9bf58092b1d4 (required)
* exJob.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* economic 1..1 BackboneElement "家庭經濟狀況" "家庭經濟狀況"
* economic.value 1..1 Coding "選項" "選項"
* economic.value from hn-vs-4a8dcdb04d9b (required)
* economic.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* hasWelfare 1..1 Coding "是否有福利" "是否有福利"
* hasWelfare from hn-vs-49fe20230ec3 (required)
* welfare 0..1 BackboneElement "福利種類" "福利種類"
* welfare.values 0..* Coding "選項" "選項"
* welfare.values from hn-vs-40193bb109d6 (required)
* welfare.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* welfare.disabilityType 0..1 Coding "身障類別" "身障類別。福利包含身障證明時必填。使用現有身心障礙類型 CodeSystem 的第一至第八類，回寫原 API 時還原完整名稱。"
* welfare.disabilityType from hn-disability-type (required)
* caregiverID 1..1 Coding "主要照顧者關係" "主要照顧者關係"
* caregiverID from hn-vs-738f974cf008 (required)
* caregiverName 1..1 string "主要照顧者姓名" "主要照顧者姓名"
* caregiverAddress 1..1 BackboneElement "主要照顧者地址" "主要照顧者地址"
* caregiverAddress.city 1..1 string "縣市" "縣市"
* caregiverAddress.area 1..1 string "鄉鎮市區" "鄉鎮市區"
* caregiverAddress.lane 1..1 string "街路門牌" "街路門牌"
* caregiverTel 1..1 string "主要照顧者電話" "主要照顧者電話"
* egyContactRelation 1..1 Coding "緊急聯絡人關係" "緊急聯絡人關係"
* egyContactRelation from hn-vs-2029890a4c12 (required)
* egyContactName 1..1 string "緊急聯絡人姓名" "緊急聯絡人姓名"
* egyContactTel1 1..1 string "緊急聯絡電話一" "緊急聯絡電話一"
* egyContactTel2 0..1 string "緊急聯絡電話二" "緊急聯絡電話二"
* nurseID 1..1 string "主責護理人員身分證字號" "主責護理人員身分證字號"
* decisionMakerRelation 1..1 BackboneElement "主要醫療決定者關係" "主要醫療決定者關係"
* decisionMakerRelation.value 1..1 Coding "選項" "選項"
* decisionMakerRelation.value from hn-vs-b63e1293c409 (required)
* decisionMakerRelation.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* mEvent 1..1 Coding "一年內是否發生重大事件" "一年內是否發生重大事件"
* mEvent from hn-vs-49fe20230ec3 (required)
* mEventItem 0..1 BackboneElement "重大事件項目" "重大事件項目"
* mEventItem.values 0..* Coding "選項" "選項"
* mEventItem.values from hn-vs-fe3736bbd09e (required)
* mEventItem.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* caseDesc 0..1 string "個案描述" "個案描述"
* createID 1..1 string "建立機構代碼" "建立機構代碼"
* medicals 0..* BackboneElement "共照醫事人員" "共照醫事人員"
* medicals.name 1..1 string "成員姓名" "成員姓名"
* medicals.careDate 0..1 date "加入日期" "加入日期"
* medicals.idNo 0..1 string "成員身分證字號" "成員身分證字號"
* medicals.jobTitle 1..1 BackboneElement "成員職稱" "成員職稱"
* medicals.jobTitle.value 1..1 Coding "選項" "選項"
* medicals.jobTitle.value from hn-vs-94d2d2fdf018 (required)
* medicals.jobTitle.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* medicals.tel 1..1 string "電話" "電話"
* medicals.careRemark 0..1 string "照護備註" "照護備註"
* relatives 0..* BackboneElement "共照親友" "共照親友"
* relatives.name 1..1 string "成員姓名" "成員姓名"
* relatives.relationship 1..1 BackboneElement "關係" "關係"
* relatives.relationship.value 1..1 Coding "選項" "選項"
* relatives.relationship.value from hn-vs-9570830f5a60 (required)
* relatives.relationship.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* relatives.careTime 1..1 BackboneElement "主要照顧時間" "主要照顧時間"
* relatives.careTime.value 1..1 Coding "選項" "選項"
* relatives.careTime.value from hn-vs-a946985c2125 (required)
* relatives.careTime.other 0..1 string "補充說明" "補充說明。選擇其他時應填寫說明。"
* relatives.tel1 1..1 BackboneElement "電話1" "電話1"
* relatives.tel1.value 1..1 string "電話號碼" "電話號碼"
* relatives.tel1.remark 0..1 string "聯絡時間與說明" "聯絡時間與說明"
* relatives.tel2 0..1 BackboneElement "電話2" "電話2"
* relatives.tel2.value 1..1 string "電話號碼" "電話號碼"
* relatives.tel2.remark 0..1 string "聯絡時間與說明" "聯絡時間與說明"
* relatives.tel3 0..1 BackboneElement "電話3" "電話3"
* relatives.tel3.value 1..1 string "電話號碼" "電話號碼"
* relatives.tel3.remark 0..1 string "聯絡時間與說明" "聯絡時間與說明"
* relatives.careRemark 0..1 string "照護備註" "照護備註"

Mapping: HNBaseDataModelToFHIR
Id: hn-basedata-fhir
Title: "居家護理－個案基本資料欄位對應"
Source: HNBaseDataModel
Target: "http://ltc-ig.fhir.tw/StructureDefinition/HNBaseDataResponse"
* caseID -> "QuestionnaireResponse.item.where(linkId='CaseID')" "來源欄位／題目：CaseID"
* endDate -> "QuestionnaireResponse.item.where(linkId='EndDate')" "來源欄位／題目：EndDate"
* caseSource -> "QuestionnaireResponse.item.where(linkId='CaseSource')" "來源欄位／題目：CaseSource"
* caseSource.value -> "QuestionnaireResponse.item.where(linkId='CaseSource').item.where(linkId='CaseSource.Value')" "來源欄位／題目：CaseSource.Value"
* caseSource.other -> "QuestionnaireResponse.item.where(linkId='CaseSource').item.where(linkId='CaseSource.Other')" "來源欄位／題目：CaseSource.Other"
* caseName -> "QuestionnaireResponse.item.where(linkId='CaseName')" "來源欄位／題目：CaseName"
* sex -> "QuestionnaireResponse.item.where(linkId='Sex')" "來源欄位／題目：Sex"
* sex.value -> "QuestionnaireResponse.item.where(linkId='Sex').item.where(linkId='Sex.Value')" "來源欄位／題目：Sex.Value"
* sex.other -> "QuestionnaireResponse.item.where(linkId='Sex').item.where(linkId='Sex.Other')" "來源欄位／題目：Sex.Other"
* caseType -> "QuestionnaireResponse.item.where(linkId='CaseType')" "來源欄位／題目：CaseType"
* birthdate -> "QuestionnaireResponse.item.where(linkId='Birthdate')" "來源欄位／題目：Birthdate"
* phoneNumber -> "QuestionnaireResponse.item.where(linkId='PhoneNumber')" "來源欄位／題目：PhoneNumber"
* address -> "QuestionnaireResponse.item.where(linkId='Address')" "來源欄位／題目：Address"
* address.city -> "QuestionnaireResponse.item.where(linkId='Address').item.where(linkId='Address.City')" "來源欄位／題目：Address.City"
* address.area -> "QuestionnaireResponse.item.where(linkId='Address').item.where(linkId='Address.Area')" "來源欄位／題目：Address.Area"
* address.lane -> "QuestionnaireResponse.item.where(linkId='Address').item.where(linkId='Address.Lane')" "來源欄位／題目：Address.Lane"
* education -> "QuestionnaireResponse.item.where(linkId='Education')" "來源欄位／題目：Education"
* education.value -> "QuestionnaireResponse.item.where(linkId='Education').item.where(linkId='Education.Value')" "來源欄位／題目：Education.Value"
* education.other -> "QuestionnaireResponse.item.where(linkId='Education').item.where(linkId='Education.Other')" "來源欄位／題目：Education.Other"
* marriage -> "QuestionnaireResponse.item.where(linkId='Marriage')" "來源欄位／題目：Marriage"
* marriage.value -> "QuestionnaireResponse.item.where(linkId='Marriage').item.where(linkId='Marriage.Value')" "來源欄位／題目：Marriage.Value"
* marriage.other -> "QuestionnaireResponse.item.where(linkId='Marriage').item.where(linkId='Marriage.Other')" "來源欄位／題目：Marriage.Other"
* religion -> "QuestionnaireResponse.item.where(linkId='Religion')" "來源欄位／題目：Religion"
* religion.value -> "QuestionnaireResponse.item.where(linkId='Religion').item.where(linkId='Religion.Value')" "來源欄位／題目：Religion.Value"
* religion.other -> "QuestionnaireResponse.item.where(linkId='Religion').item.where(linkId='Religion.Other')" "來源欄位／題目：Religion.Other"
* exJob -> "QuestionnaireResponse.item.where(linkId='ExJob')" "來源欄位／題目：ExJob"
* exJob.value -> "QuestionnaireResponse.item.where(linkId='ExJob').item.where(linkId='ExJob.Value')" "來源欄位／題目：ExJob.Value"
* exJob.other -> "QuestionnaireResponse.item.where(linkId='ExJob').item.where(linkId='ExJob.Other')" "來源欄位／題目：ExJob.Other"
* economic -> "QuestionnaireResponse.item.where(linkId='Economic')" "來源欄位／題目：Economic"
* economic.value -> "QuestionnaireResponse.item.where(linkId='Economic').item.where(linkId='Economic.Value')" "來源欄位／題目：Economic.Value"
* economic.other -> "QuestionnaireResponse.item.where(linkId='Economic').item.where(linkId='Economic.Other')" "來源欄位／題目：Economic.Other"
* hasWelfare -> "QuestionnaireResponse.item.where(linkId='HasWelfare')" "來源欄位／題目：HasWelfare"
* welfare -> "QuestionnaireResponse.item.where(linkId='Welfare')" "來源欄位／題目：Welfare"
* welfare.values -> "QuestionnaireResponse.item.where(linkId='Welfare').item.where(linkId='Welfare.Values')" "來源欄位／題目：Welfare.Values"
* welfare.other -> "QuestionnaireResponse.item.where(linkId='Welfare').item.where(linkId='Welfare.Other')" "來源欄位／題目：Welfare.Other"
* welfare.disabilityType -> "QuestionnaireResponse.item.where(linkId='Welfare').item.where(linkId='Welfare.DisabilityType')" "來源欄位／題目：Welfare.DisabilityType"
* caregiverID -> "QuestionnaireResponse.item.where(linkId='CaregiverID')" "來源欄位／題目：CaregiverID"
* caregiverName -> "QuestionnaireResponse.item.where(linkId='CaregiverName')" "來源欄位／題目：CaregiverName"
* caregiverAddress -> "QuestionnaireResponse.item.where(linkId='CaregiverAddress')" "來源欄位／題目：CaregiverAddress"
* caregiverAddress.city -> "QuestionnaireResponse.item.where(linkId='CaregiverAddress').item.where(linkId='CaregiverAddress.City')" "來源欄位／題目：CaregiverAddress.City"
* caregiverAddress.area -> "QuestionnaireResponse.item.where(linkId='CaregiverAddress').item.where(linkId='CaregiverAddress.Area')" "來源欄位／題目：CaregiverAddress.Area"
* caregiverAddress.lane -> "QuestionnaireResponse.item.where(linkId='CaregiverAddress').item.where(linkId='CaregiverAddress.Lane')" "來源欄位／題目：CaregiverAddress.Lane"
* caregiverTel -> "QuestionnaireResponse.item.where(linkId='CaregiverTel')" "來源欄位／題目：CaregiverTel"
* egyContactRelation -> "QuestionnaireResponse.item.where(linkId='EgyContactRelation')" "來源欄位／題目：EgyContactRelation"
* egyContactName -> "QuestionnaireResponse.item.where(linkId='EgyContactName')" "來源欄位／題目：EgyContactName"
* egyContactTel1 -> "QuestionnaireResponse.item.where(linkId='EgyContactTel1')" "來源欄位／題目：EgyContactTel1"
* egyContactTel2 -> "QuestionnaireResponse.item.where(linkId='EgyContactTel2')" "來源欄位／題目：EgyContactTel2"
* nurseID -> "QuestionnaireResponse.item.where(linkId='NurseID')" "來源欄位／題目：NurseID"
* decisionMakerRelation -> "QuestionnaireResponse.item.where(linkId='DecisionMakerRelation')" "來源欄位／題目：DecisionMakerRelation"
* decisionMakerRelation.value -> "QuestionnaireResponse.item.where(linkId='DecisionMakerRelation').item.where(linkId='DecisionMakerRelation.Value')" "來源欄位／題目：DecisionMakerRelation.Value"
* decisionMakerRelation.other -> "QuestionnaireResponse.item.where(linkId='DecisionMakerRelation').item.where(linkId='DecisionMakerRelation.Other')" "來源欄位／題目：DecisionMakerRelation.Other"
* mEvent -> "QuestionnaireResponse.item.where(linkId='MEvent')" "來源欄位／題目：MEvent"
* mEventItem -> "QuestionnaireResponse.item.where(linkId='MEventItem')" "來源欄位／題目：MEventItem"
* mEventItem.values -> "QuestionnaireResponse.item.where(linkId='MEventItem').item.where(linkId='MEventItem.Values')" "來源欄位／題目：MEventItem.Values"
* mEventItem.other -> "QuestionnaireResponse.item.where(linkId='MEventItem').item.where(linkId='MEventItem.Other')" "來源欄位／題目：MEventItem.Other"
* caseDesc -> "QuestionnaireResponse.item.where(linkId='CaseDesc')" "來源欄位／題目：CaseDesc"
* createID -> "QuestionnaireResponse.item.where(linkId='CreateID')" "來源欄位／題目：CreateID"
* medicals -> "QuestionnaireResponse.item.where(linkId='Medicals')" "來源欄位／題目：Medicals"
* medicals.name -> "QuestionnaireResponse.item.where(linkId='Medicals').item.where(linkId='Medicals.Name')" "來源欄位／題目：Medicals.Name"
* medicals.careDate -> "QuestionnaireResponse.item.where(linkId='Medicals').item.where(linkId='Medicals.CareDate')" "來源欄位／題目：Medicals.CareDate"
* medicals.idNo -> "QuestionnaireResponse.item.where(linkId='Medicals').item.where(linkId='Medicals.IdNo')" "來源欄位／題目：Medicals.IdNo"
* medicals.jobTitle -> "QuestionnaireResponse.item.where(linkId='Medicals').item.where(linkId='Medicals.JobTitle')" "來源欄位／題目：Medicals.JobTitle"
* medicals.jobTitle.value -> "QuestionnaireResponse.item.where(linkId='Medicals').item.where(linkId='Medicals.JobTitle').item.where(linkId='Medicals.JobTitle.Value')" "來源欄位／題目：Medicals.JobTitle.Value"
* medicals.jobTitle.other -> "QuestionnaireResponse.item.where(linkId='Medicals').item.where(linkId='Medicals.JobTitle').item.where(linkId='Medicals.JobTitle.Other')" "來源欄位／題目：Medicals.JobTitle.Other"
* medicals.tel -> "QuestionnaireResponse.item.where(linkId='Medicals').item.where(linkId='Medicals.Tel')" "來源欄位／題目：Medicals.Tel"
* medicals.careRemark -> "QuestionnaireResponse.item.where(linkId='Medicals').item.where(linkId='Medicals.CareRemark')" "來源欄位／題目：Medicals.CareRemark"
* relatives -> "QuestionnaireResponse.item.where(linkId='Relatives')" "來源欄位／題目：Relatives"
* relatives.name -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Name')" "來源欄位／題目：Relatives.Name"
* relatives.relationship -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Relationship')" "來源欄位／題目：Relatives.Relationship"
* relatives.relationship.value -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Relationship').item.where(linkId='Relatives.Relationship.Value')" "來源欄位／題目：Relatives.Relationship.Value"
* relatives.relationship.other -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Relationship').item.where(linkId='Relatives.Relationship.Other')" "來源欄位／題目：Relatives.Relationship.Other"
* relatives.careTime -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.CareTime')" "來源欄位／題目：Relatives.CareTime"
* relatives.careTime.value -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.CareTime').item.where(linkId='Relatives.CareTime.Value')" "來源欄位／題目：Relatives.CareTime.Value"
* relatives.careTime.other -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.CareTime').item.where(linkId='Relatives.CareTime.Other')" "來源欄位／題目：Relatives.CareTime.Other"
* relatives.tel1 -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Tel1')" "來源欄位／題目：Relatives.Tel1"
* relatives.tel1.value -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Tel1').item.where(linkId='Relatives.Tel1.Value')" "來源欄位／題目：Relatives.Tel1.Value"
* relatives.tel1.remark -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Tel1').item.where(linkId='Relatives.Tel1.Remark')" "來源欄位／題目：Relatives.Tel1.Remark"
* relatives.tel2 -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Tel2')" "來源欄位／題目：Relatives.Tel2"
* relatives.tel2.value -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Tel2').item.where(linkId='Relatives.Tel2.Value')" "來源欄位／題目：Relatives.Tel2.Value"
* relatives.tel2.remark -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Tel2').item.where(linkId='Relatives.Tel2.Remark')" "來源欄位／題目：Relatives.Tel2.Remark"
* relatives.tel3 -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Tel3')" "來源欄位／題目：Relatives.Tel3"
* relatives.tel3.value -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Tel3').item.where(linkId='Relatives.Tel3.Value')" "來源欄位／題目：Relatives.Tel3.Value"
* relatives.tel3.remark -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.Tel3').item.where(linkId='Relatives.Tel3.Remark')" "來源欄位／題目：Relatives.Tel3.Remark"
* relatives.careRemark -> "QuestionnaireResponse.item.where(linkId='Relatives').item.where(linkId='Relatives.CareRemark')" "來源欄位／題目：Relatives.CareRemark"
