Logical: HNFallRisksModel
Id: HNFallRisksModel
Title: "居家護理－跌倒危險性評估邏輯模型"
Description: "描述居家護理跌倒危險性評估的資料需求。依 V5.0.16 有效欄位建立，來源欄位對應另列於 Mapping。"
* ^status = #draft
* ^version = "5.0.16"
* date 1..1 date "紀錄日期" "紀錄日期"
* nurseID 1..1 string "護理人員身分證字號" "護理人員身分證字號"
* questions 1..1 BackboneElement "評估項目" "評估項目"
* questions.q2f552b4a 1..1 BackboneElement "年紀65歲以上" "年紀65歲以上"
* questions.q2f552b4a.answer 1..1 Coding "評估答案" "評估答案"
* questions.q2f552b4a.answer from hn-vs-58e4d598f859 (required)
* questions.q2f552b4a.options 0..1 string "多選答案" "多選答案"
* questions.q2f552b4a.other 0..1 string "其他用藥說明" "其他用藥說明"
* questions.q463dc41d 1..1 BackboneElement "過去一年內曾跌倒" "過去一年內曾跌倒"
* questions.q463dc41d.answer 1..1 Coding "評估答案" "評估答案"
* questions.q463dc41d.answer from hn-vs-58e4d598f859 (required)
* questions.q463dc41d.options 0..1 string "多選答案" "多選答案"
* questions.q463dc41d.other 0..1 string "其他用藥說明" "其他用藥說明"
* questions.qd680c277 1..1 BackboneElement "最近意識/認知出現異常" "最近意識/認知出現異常"
* questions.qd680c277.answer 1..1 Coding "評估答案" "評估答案"
* questions.qd680c277.answer from hn-vs-58e4d598f859 (required)
* questions.qd680c277.options 0..1 string "多選答案" "多選答案"
* questions.qd680c277.other 0..1 string "其他用藥說明" "其他用藥說明"
* questions.qc1c1fb2c 1..1 BackboneElement "活動功能異常" "活動功能異常"
* questions.qc1c1fb2c.answer 1..1 Coding "評估答案" "評估答案"
* questions.qc1c1fb2c.answer from hn-vs-58e4d598f859 (required)
* questions.qc1c1fb2c.options 0..1 string "多選答案" "多選答案"
* questions.qc1c1fb2c.other 0..1 string "其他用藥說明" "其他用藥說明"
* questions.q603c2de9 1..1 BackboneElement "體能虛弱" "體能虛弱"
* questions.q603c2de9.answer 1..1 Coding "評估答案" "評估答案"
* questions.q603c2de9.answer from hn-vs-58e4d598f859 (required)
* questions.q603c2de9.options 0..1 string "多選答案" "多選答案"
* questions.q603c2de9.other 0..1 string "其他用藥說明" "其他用藥說明"
* questions.qbf720dbc 1..1 BackboneElement "知覺障礙" "知覺障礙"
* questions.qbf720dbc.answer 1..1 Coding "評估答案" "評估答案"
* questions.qbf720dbc.answer from hn-vs-58e4d598f859 (required)
* questions.qbf720dbc.options 0..1 string "多選答案" "多選答案"
* questions.qbf720dbc.other 0..1 string "其他用藥說明" "其他用藥說明"
* questions.q6fa60520 1..1 BackboneElement "暈眩/低血壓" "暈眩/低血壓"
* questions.q6fa60520.answer 1..1 Coding "評估答案" "評估答案"
* questions.q6fa60520.answer from hn-vs-58e4d598f859 (required)
* questions.q6fa60520.options 0..1 string "多選答案" "多選答案"
* questions.q6fa60520.other 0..1 string "其他用藥說明" "其他用藥說明"
* questions.qe6e35ded 1..1 BackboneElement "使用藥物" "使用藥物"
* questions.qe6e35ded.answer 1..1 Coding "評估答案" "評估答案"
* questions.qe6e35ded.answer from hn-vs-58e4d598f859 (required)
* questions.qe6e35ded.options 0..1 string "多選答案" "多選答案"
* questions.qe6e35ded.other 0..1 string "其他用藥說明" "其他用藥說明"
* isTemporary 0..1 Coding "是否暫存" "是否暫存"
* isTemporary from hn-vs-58e4d598f859 (required)

Mapping: HNFallRisksModelToFHIR
Id: hn-fallrisks-fhir
Title: "居家護理－跌倒危險性評估欄位對應"
Source: HNFallRisksModel
Target: "http://ltc-ig.fhir.tw/StructureDefinition/HNFallRisksResponse"
* date -> "QuestionnaireResponse.item.where(linkId='Date')" "來源欄位／題目：Date"
* nurseID -> "QuestionnaireResponse.item.where(linkId='NurseID')" "來源欄位／題目：NurseID"
* questions -> "QuestionnaireResponse.item.where(linkId='Questions')" "來源欄位／題目：Questions"
* questions.q2f552b4a -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q2f552b4a')" "來源欄位／題目：Questions[Question='年紀65歲以上']"
* questions.q2f552b4a.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q2f552b4a').item.where(linkId='Questions.q2f552b4a.Answer')" "來源欄位／題目：Questions[Question='年紀65歲以上'].Answer"
* questions.q2f552b4a.options -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q2f552b4a').item.where(linkId='Questions.q2f552b4a.Options')" "來源欄位／題目：Questions[Question='年紀65歲以上'].Options"
* questions.q2f552b4a.other -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q2f552b4a').item.where(linkId='Questions.q2f552b4a.Other')" "來源欄位／題目：Questions[Question='年紀65歲以上'].Other"
* questions.q463dc41d -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q463dc41d')" "來源欄位／題目：Questions[Question='過去一年內曾跌倒']"
* questions.q463dc41d.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q463dc41d').item.where(linkId='Questions.q463dc41d.Answer')" "來源欄位／題目：Questions[Question='過去一年內曾跌倒'].Answer"
* questions.q463dc41d.options -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q463dc41d').item.where(linkId='Questions.q463dc41d.Options')" "來源欄位／題目：Questions[Question='過去一年內曾跌倒'].Options"
* questions.q463dc41d.other -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q463dc41d').item.where(linkId='Questions.q463dc41d.Other')" "來源欄位／題目：Questions[Question='過去一年內曾跌倒'].Other"
* questions.qd680c277 -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qd680c277')" "來源欄位／題目：Questions[Question='最近意識/認知出現異常']"
* questions.qd680c277.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qd680c277').item.where(linkId='Questions.qd680c277.Answer')" "來源欄位／題目：Questions[Question='最近意識/認知出現異常'].Answer"
* questions.qd680c277.options -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qd680c277').item.where(linkId='Questions.qd680c277.Options')" "來源欄位／題目：Questions[Question='最近意識/認知出現異常'].Options"
* questions.qd680c277.other -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qd680c277').item.where(linkId='Questions.qd680c277.Other')" "來源欄位／題目：Questions[Question='最近意識/認知出現異常'].Other"
* questions.qc1c1fb2c -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qc1c1fb2c')" "來源欄位／題目：Questions[Question='活動功能異常']"
* questions.qc1c1fb2c.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qc1c1fb2c').item.where(linkId='Questions.qc1c1fb2c.Answer')" "來源欄位／題目：Questions[Question='活動功能異常'].Answer"
* questions.qc1c1fb2c.options -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qc1c1fb2c').item.where(linkId='Questions.qc1c1fb2c.Options')" "來源欄位／題目：Questions[Question='活動功能異常'].Options"
* questions.qc1c1fb2c.other -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qc1c1fb2c').item.where(linkId='Questions.qc1c1fb2c.Other')" "來源欄位／題目：Questions[Question='活動功能異常'].Other"
* questions.q603c2de9 -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q603c2de9')" "來源欄位／題目：Questions[Question='體能虛弱']"
* questions.q603c2de9.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q603c2de9').item.where(linkId='Questions.q603c2de9.Answer')" "來源欄位／題目：Questions[Question='體能虛弱'].Answer"
* questions.q603c2de9.options -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q603c2de9').item.where(linkId='Questions.q603c2de9.Options')" "來源欄位／題目：Questions[Question='體能虛弱'].Options"
* questions.q603c2de9.other -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q603c2de9').item.where(linkId='Questions.q603c2de9.Other')" "來源欄位／題目：Questions[Question='體能虛弱'].Other"
* questions.qbf720dbc -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qbf720dbc')" "來源欄位／題目：Questions[Question='知覺障礙']"
* questions.qbf720dbc.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qbf720dbc').item.where(linkId='Questions.qbf720dbc.Answer')" "來源欄位／題目：Questions[Question='知覺障礙'].Answer"
* questions.qbf720dbc.options -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qbf720dbc').item.where(linkId='Questions.qbf720dbc.Options')" "來源欄位／題目：Questions[Question='知覺障礙'].Options"
* questions.qbf720dbc.other -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qbf720dbc').item.where(linkId='Questions.qbf720dbc.Other')" "來源欄位／題目：Questions[Question='知覺障礙'].Other"
* questions.q6fa60520 -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q6fa60520')" "來源欄位／題目：Questions[Question='暈眩/低血壓']"
* questions.q6fa60520.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q6fa60520').item.where(linkId='Questions.q6fa60520.Answer')" "來源欄位／題目：Questions[Question='暈眩/低血壓'].Answer"
* questions.q6fa60520.options -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q6fa60520').item.where(linkId='Questions.q6fa60520.Options')" "來源欄位／題目：Questions[Question='暈眩/低血壓'].Options"
* questions.q6fa60520.other -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.q6fa60520').item.where(linkId='Questions.q6fa60520.Other')" "來源欄位／題目：Questions[Question='暈眩/低血壓'].Other"
* questions.qe6e35ded -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qe6e35ded')" "來源欄位／題目：Questions[Question='使用藥物']"
* questions.qe6e35ded.answer -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qe6e35ded').item.where(linkId='Questions.qe6e35ded.Answer')" "來源欄位／題目：Questions[Question='使用藥物'].Answer"
* questions.qe6e35ded.options -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qe6e35ded').item.where(linkId='Questions.qe6e35ded.Options')" "來源欄位／題目：Questions[Question='使用藥物'].Options"
* questions.qe6e35ded.other -> "QuestionnaireResponse.item.where(linkId='Questions').item.where(linkId='Questions.qe6e35ded').item.where(linkId='Questions.qe6e35ded.Other')" "來源欄位／題目：Questions[Question='使用藥物'].Other"
* isTemporary -> "QuestionnaireResponse.item.where(linkId='IsTemporary')" "來源欄位／題目：IsTemporary"
