Logical: HNBodyEvaluationsModel
Id: HNBodyEvaluationsModel
Title: "居家護理－身體評估評估邏輯模型"
Description: "描述居家護理身體評估評估的資料需求。依 V5.0.16 有效欄位建立，來源欄位對應另列於 Mapping。"
* ^status = #draft
* ^version = "5.0.16"
* date 1..1 date "紀錄日期" "紀錄日期"
* nurseID 1..1 string "護理人員身分證字號" "護理人員身分證字號"
* bodyQuestions 1..1 BackboneElement "評估項目" "評估項目"
* bodyQuestions.q3d5455cd 1..1 BackboneElement "睜眼" "睜眼"
* bodyQuestions.q3d5455cd.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q3d5455cd.answer from hn-vs-6380f9a50deb (required)
* bodyQuestions.q3d5455cd.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q3d5455cd.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q78be3cfc 1..1 BackboneElement "語言" "語言"
* bodyQuestions.q78be3cfc.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q78be3cfc.answer from hn-vs-d2f289370ed0 (required)
* bodyQuestions.q78be3cfc.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q78be3cfc.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qd5d3ea28 1..1 BackboneElement "運動" "運動"
* bodyQuestions.qd5d3ea28.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qd5d3ea28.answer from hn-vs-784e3567e13b (required)
* bodyQuestions.qd5d3ea28.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.qd5d3ea28.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q9999e6f5 1..1 BackboneElement "視力" "視力"
* bodyQuestions.q9999e6f5.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q9999e6f5.answer from hn-vs-ef4daeacd99a (required)
* bodyQuestions.q9999e6f5.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q9999e6f5.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qcd3cc2c1 1..1 BackboneElement "視力-部位" "視力-部位"
* bodyQuestions.qcd3cc2c1.answer 0..1 string "評估答案" "評估答案。本題單選答案留空；填寫多選答案。"
* bodyQuestions.qcd3cc2c1.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.qcd3cc2c1.multipleAnswer from hn-vs-2fd20e6427ff (required)
* bodyQuestions.qcd3cc2c1.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q99290406 1..1 BackboneElement "視力-影響日常活動" "視力-影響日常活動"
* bodyQuestions.q99290406.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q99290406.answer from hn-vs-58e4d598f859 (required)
* bodyQuestions.q99290406.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q99290406.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q24eedc1b 1..1 BackboneElement "視力-輔具" "視力-輔具"
* bodyQuestions.q24eedc1b.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q24eedc1b.answer from hn-vs-49fe20230ec3 (required)
* bodyQuestions.q24eedc1b.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q24eedc1b.multipleAnswer from hn-vs-afadc3bb2a88 (required)
* bodyQuestions.q24eedc1b.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q6215056f 1..1 BackboneElement "聽力" "聽力"
* bodyQuestions.q6215056f.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q6215056f.answer from hn-vs-ef4daeacd99a (required)
* bodyQuestions.q6215056f.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q6215056f.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q1678a5f1 1..1 BackboneElement "聽力-部位" "聽力-部位"
* bodyQuestions.q1678a5f1.answer 0..1 string "評估答案" "評估答案。本題單選答案留空；填寫多選答案。"
* bodyQuestions.q1678a5f1.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q1678a5f1.multipleAnswer from hn-vs-7bc89358fe37 (required)
* bodyQuestions.q1678a5f1.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q93005aaa 1..1 BackboneElement "聽力-影響日常活動" "聽力-影響日常活動"
* bodyQuestions.q93005aaa.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q93005aaa.answer from hn-vs-58e4d598f859 (required)
* bodyQuestions.q93005aaa.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q93005aaa.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q2386d883 1..1 BackboneElement "聽力-輔具" "聽力-輔具"
* bodyQuestions.q2386d883.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q2386d883.answer from hn-vs-49fe20230ec3 (required)
* bodyQuestions.q2386d883.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q2386d883.multipleAnswer from hn-vs-f0b4522906b6 (required)
* bodyQuestions.q2386d883.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q306e4676 1..1 BackboneElement "溝通" "溝通"
* bodyQuestions.q306e4676.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q306e4676.answer from hn-vs-0655870f5454 (required)
* bodyQuestions.q306e4676.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q306e4676.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q63b2fbbe 1..1 BackboneElement "溝通-影響日常活動" "溝通-影響日常活動"
* bodyQuestions.q63b2fbbe.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q63b2fbbe.answer from hn-vs-d9301962abbf (required)
* bodyQuestions.q63b2fbbe.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q63b2fbbe.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q3288f369 1..1 BackboneElement "說話" "說話"
* bodyQuestions.q3288f369.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q3288f369.answer from hn-vs-3330cbe2f937 (required)
* bodyQuestions.q3288f369.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q3288f369.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q14304745 1..1 BackboneElement "理解" "理解"
* bodyQuestions.q14304745.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q14304745.answer from hn-vs-dc054900d0e6 (required)
* bodyQuestions.q14304745.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q14304745.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q7ca654d9 1..1 BackboneElement "口腔外觀" "口腔外觀"
* bodyQuestions.q7ca654d9.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q7ca654d9.answer from hn-vs-7c98e63372ac (required)
* bodyQuestions.q7ca654d9.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q7ca654d9.multipleAnswer from hn-vs-415683173294 (required)
* bodyQuestions.q7ca654d9.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q53fb7d09 1..1 BackboneElement "特殊進食" "特殊進食"
* bodyQuestions.q53fb7d09.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q53fb7d09.answer from hn-vs-49fe20230ec3 (required)
* bodyQuestions.q53fb7d09.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q53fb7d09.multipleAnswer from hn-vs-3435b7eace88 (required)
* bodyQuestions.q53fb7d09.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qfcd3bd60 1..1 BackboneElement "假牙狀況" "假牙狀況"
* bodyQuestions.qfcd3bd60.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qfcd3bd60.answer from hn-vs-a051b2c062af (required)
* bodyQuestions.qfcd3bd60.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.qfcd3bd60.multipleAnswer from hn-vs-eee6be407d0e (required)
* bodyQuestions.qfcd3bd60.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q7b3136eb 1..1 BackboneElement "腹部狀態" "腹部狀態"
* bodyQuestions.q7b3136eb.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q7b3136eb.answer from hn-vs-b42a51b1139e (required)
* bodyQuestions.q7b3136eb.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q7b3136eb.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qc0a49d43 1..1 BackboneElement "腸蠕動" "腸蠕動"
* bodyQuestions.qc0a49d43.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qc0a49d43.answer from hn-vs-3d4ed1f2575b (required)
* bodyQuestions.qc0a49d43.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.qc0a49d43.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qd49ab702 1..1 BackboneElement "消化狀態" "消化狀態"
* bodyQuestions.qd49ab702.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qd49ab702.answer from hn-vs-7ce3f119b854 (required)
* bodyQuestions.qd49ab702.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.qd49ab702.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q1b2dc66c 1..1 BackboneElement "排便型態" "排便型態"
* bodyQuestions.q1b2dc66c.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q1b2dc66c.answer from hn-vs-7f8a5cfdf9c9 (required)
* bodyQuestions.q1b2dc66c.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q1b2dc66c.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qfaaaf47f 1..1 BackboneElement "排便顏色" "排便顏色"
* bodyQuestions.qfaaaf47f.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qfaaaf47f.answer from hn-vs-a88d0ac6ee1a (required)
* bodyQuestions.qfaaaf47f.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.qfaaaf47f.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qbfd21c82 1..1 BackboneElement "排便輔助" "排便輔助"
* bodyQuestions.qbfd21c82.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qbfd21c82.answer from hn-vs-19264db8df7b (required)
* bodyQuestions.qbfd21c82.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.qbfd21c82.multipleAnswer from hn-vs-0467df08a056 (required)
* bodyQuestions.qbfd21c82.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q0cdace56 1..1 BackboneElement "排尿型態" "排尿型態"
* bodyQuestions.q0cdace56.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q0cdace56.answer from hn-vs-5cb9bbd6d620 (required)
* bodyQuestions.q0cdace56.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q0cdace56.multipleAnswer from hn-vs-b5e899beaa3a (required)
* bodyQuestions.q0cdace56.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q3170f977 1..1 BackboneElement "排尿顏色" "排尿顏色"
* bodyQuestions.q3170f977.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q3170f977.answer from hn-vs-c0e4f2d08eec (required)
* bodyQuestions.q3170f977.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q3170f977.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q1dddcc0f 1..1 BackboneElement "排尿輔助" "排尿輔助"
* bodyQuestions.q1dddcc0f.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q1dddcc0f.answer from hn-vs-19264db8df7b (required)
* bodyQuestions.q1dddcc0f.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q1dddcc0f.multipleAnswer from hn-vs-ec686161641f (required)
* bodyQuestions.q1dddcc0f.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q889a3f5d 1..1 BackboneElement "溫度" "溫度"
* bodyQuestions.q889a3f5d.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q889a3f5d.answer from hn-vs-13d13792ca45 (required)
* bodyQuestions.q889a3f5d.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q889a3f5d.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qfbbbe51d 1..1 BackboneElement "濕度" "濕度"
* bodyQuestions.qfbbbe51d.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qfbbbe51d.answer from hn-vs-acfe4f6c5f3a (required)
* bodyQuestions.qfbbbe51d.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.qfbbbe51d.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q2edc1f98 1..1 BackboneElement "顏色" "顏色"
* bodyQuestions.q2edc1f98.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q2edc1f98.answer from hn-vs-ed3fafa578d2 (required)
* bodyQuestions.q2edc1f98.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q2edc1f98.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q0aec089c 1..1 BackboneElement "水腫級數" "水腫級數"
* bodyQuestions.q0aec089c.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q0aec089c.answer from hn-vs-49fe20230ec3 (required)
* bodyQuestions.q0aec089c.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q0aec089c.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q5b3534e0 1..1 BackboneElement "水腫等級" "水腫等級"
* bodyQuestions.q5b3534e0.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q5b3534e0.answer from hn-vs-c93d67023284 (required)
* bodyQuestions.q5b3534e0.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q5b3534e0.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q6e6e5811 1..1 BackboneElement "完整" "完整"
* bodyQuestions.q6e6e5811.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q6e6e5811.answer from hn-vs-58e4d598f859 (required)
* bodyQuestions.q6e6e5811.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q6e6e5811.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q4c713f60 1..1 BackboneElement "左上肢" "左上肢"
* bodyQuestions.q4c713f60.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q4c713f60.answer from hn-vs-00697b86a7bc (required)
* bodyQuestions.q4c713f60.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q4c713f60.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q43c26e48 1..1 BackboneElement "右上肢" "右上肢"
* bodyQuestions.q43c26e48.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q43c26e48.answer from hn-vs-00697b86a7bc (required)
* bodyQuestions.q43c26e48.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q43c26e48.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q9926c640 1..1 BackboneElement "左下肢" "左下肢"
* bodyQuestions.q9926c640.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q9926c640.answer from hn-vs-00697b86a7bc (required)
* bodyQuestions.q9926c640.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q9926c640.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q3f44d138 1..1 BackboneElement "右下肢" "右下肢"
* bodyQuestions.q3f44d138.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q3f44d138.answer from hn-vs-00697b86a7bc (required)
* bodyQuestions.q3f44d138.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q3f44d138.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qcd675f81 1..1 BackboneElement "行動能力問題" "行動能力問題"
* bodyQuestions.qcd675f81.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qcd675f81.answer from hn-vs-1ffa1d5d3bef (required)
* bodyQuestions.qcd675f81.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.qcd675f81.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q3adf788d 1..1 BackboneElement "肌力-輔具" "肌力-輔具"
* bodyQuestions.q3adf788d.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q3adf788d.answer from hn-vs-49fe20230ec3 (required)
* bodyQuestions.q3adf788d.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q3adf788d.multipleAnswer from hn-vs-1a72d15a5965 (required)
* bodyQuestions.q3adf788d.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q4ce17519 1..1 BackboneElement "跌倒" "跌倒"
* bodyQuestions.q4ce17519.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q4ce17519.answer from hn-vs-19264db8df7b (required)
* bodyQuestions.q4ce17519.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q4ce17519.multipleAnswer from hn-vs-3bbfa4b4f8db (required)
* bodyQuestions.q4ce17519.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qcc99d785 1..1 BackboneElement "跌倒次數" "跌倒次數"
* bodyQuestions.qcc99d785.answer 1..1 string "評估答案" "評估答案"
* bodyQuestions.qcc99d785.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.qcc99d785.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q1ea67d8d 1..1 BackboneElement "行為" "行為"
* bodyQuestions.q1ea67d8d.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q1ea67d8d.answer from hn-vs-365bfce838bb (required)
* bodyQuestions.q1ea67d8d.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q1ea67d8d.multipleAnswer from hn-vs-46c8866533a0 (required)
* bodyQuestions.q1ea67d8d.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qca5f735b 1..1 BackboneElement "睡眠" "睡眠"
* bodyQuestions.qca5f735b.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qca5f735b.answer from hn-vs-ef4daeacd99a (required)
* bodyQuestions.qca5f735b.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.qca5f735b.multipleAnswer from hn-vs-c34dc3f43d82 (required)
* bodyQuestions.qca5f735b.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qd8db9643 1..1 BackboneElement "服用藥物" "服用藥物"
* bodyQuestions.qd8db9643.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qd8db9643.answer from hn-vs-49fe20230ec3 (required)
* bodyQuestions.qd8db9643.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.qd8db9643.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q65b57fd8 1..1 BackboneElement "藥物類別" "藥物類別"
* bodyQuestions.q65b57fd8.answer 0..1 string "評估答案" "評估答案。本題單選答案留空；填寫多選答案。"
* bodyQuestions.q65b57fd8.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q65b57fd8.multipleAnswer from hn-vs-6d733f47d6f4 (required)
* bodyQuestions.q65b57fd8.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q03fdb3f1 1..1 BackboneElement "服用頻率" "服用頻率"
* bodyQuestions.q03fdb3f1.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q03fdb3f1.answer from hn-vs-cf479df80e62 (required)
* bodyQuestions.q03fdb3f1.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q03fdb3f1.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.qd30f4212 1..1 BackboneElement "輔助器" "輔助器"
* bodyQuestions.qd30f4212.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.qd30f4212.answer from hn-vs-49fe20230ec3 (required)
* bodyQuestions.qd30f4212.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.qd30f4212.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q1355f181 1..1 BackboneElement "有輔助器" "有輔助器"
* bodyQuestions.q1355f181.answer 1..1 Coding "評估答案" "評估答案"
* bodyQuestions.q1355f181.answer from hn-vs-8aa8b9aed3b2 (required)
* bodyQuestions.q1355f181.multipleAnswer 0..* Coding "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q1355f181.multipleAnswer from hn-vs-1c644096303f (required)
* bodyQuestions.q1355f181.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q1c902f78 1..1 BackboneElement "鼻導管" "鼻導管"
* bodyQuestions.q1c902f78.answer 1..1 string "評估答案" "評估答案"
* bodyQuestions.q1c902f78.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。來源為逗號分隔字串。FHIR 使用多筆 Coding 答案，回寫時依序以逗號串接。"
* bodyQuestions.q1c902f78.other 0..1 string "補充說明" "補充說明"
* bodyQuestions.q6772dc09 1..1 BackboneElement "氧氣面罩" "氧氣面罩"
* bodyQuestions.q6772dc09.answer 1..1 string "評估答案" "評估答案"
* bodyQuestions.q6772dc09.multipleAnswer 0..1 string "評估多選答案" "評估多選答案。以逗號分隔選項；視力與聽力部位使用此欄。"
* bodyQuestions.q6772dc09.other 0..1 string "補充說明" "補充說明"
* isTemporary 0..1 Coding "是否暫存" "是否暫存"
* isTemporary from hn-vs-58e4d598f859 (required)

Mapping: HNBodyEvaluationsModelToFHIR
Id: hn-bodyevaluations-fhir
Title: "居家護理－身體評估評估欄位對應"
Source: HNBodyEvaluationsModel
Target: "http://ltc-ig.fhir.tw/StructureDefinition/HNBodyEvaluationsResponse"
* date -> "QuestionnaireResponse.item.where(linkId='Date')" "來源欄位／題目：Date"
* nurseID -> "QuestionnaireResponse.item.where(linkId='NurseID')" "來源欄位／題目：NurseID"
* bodyQuestions -> "QuestionnaireResponse.item.where(linkId='BodyQuestions')" "來源欄位／題目：BodyQuestions"
* bodyQuestions.q3d5455cd -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3d5455cd')" "來源欄位／題目：BodyQuestions[Question='睜眼']"
* bodyQuestions.q3d5455cd.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3d5455cd').item.where(linkId='BodyQuestions.q3d5455cd.Answer')" "來源欄位／題目：BodyQuestions[Question='睜眼'].Answer"
* bodyQuestions.q3d5455cd.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3d5455cd').item.where(linkId='BodyQuestions.q3d5455cd.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='睜眼'].MultipleAnswer"
* bodyQuestions.q3d5455cd.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3d5455cd').item.where(linkId='BodyQuestions.q3d5455cd.Other')" "來源欄位／題目：BodyQuestions[Question='睜眼'].Other"
* bodyQuestions.q78be3cfc -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q78be3cfc')" "來源欄位／題目：BodyQuestions[Question='語言']"
* bodyQuestions.q78be3cfc.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q78be3cfc').item.where(linkId='BodyQuestions.q78be3cfc.Answer')" "來源欄位／題目：BodyQuestions[Question='語言'].Answer"
* bodyQuestions.q78be3cfc.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q78be3cfc').item.where(linkId='BodyQuestions.q78be3cfc.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='語言'].MultipleAnswer"
* bodyQuestions.q78be3cfc.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q78be3cfc').item.where(linkId='BodyQuestions.q78be3cfc.Other')" "來源欄位／題目：BodyQuestions[Question='語言'].Other"
* bodyQuestions.qd5d3ea28 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd5d3ea28')" "來源欄位／題目：BodyQuestions[Question='運動']"
* bodyQuestions.qd5d3ea28.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd5d3ea28').item.where(linkId='BodyQuestions.qd5d3ea28.Answer')" "來源欄位／題目：BodyQuestions[Question='運動'].Answer"
* bodyQuestions.qd5d3ea28.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd5d3ea28').item.where(linkId='BodyQuestions.qd5d3ea28.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='運動'].MultipleAnswer"
* bodyQuestions.qd5d3ea28.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd5d3ea28').item.where(linkId='BodyQuestions.qd5d3ea28.Other')" "來源欄位／題目：BodyQuestions[Question='運動'].Other"
* bodyQuestions.q9999e6f5 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q9999e6f5')" "來源欄位／題目：BodyQuestions[Question='視力']"
* bodyQuestions.q9999e6f5.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q9999e6f5').item.where(linkId='BodyQuestions.q9999e6f5.Answer')" "來源欄位／題目：BodyQuestions[Question='視力'].Answer"
* bodyQuestions.q9999e6f5.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q9999e6f5').item.where(linkId='BodyQuestions.q9999e6f5.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='視力'].MultipleAnswer"
* bodyQuestions.q9999e6f5.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q9999e6f5').item.where(linkId='BodyQuestions.q9999e6f5.Other')" "來源欄位／題目：BodyQuestions[Question='視力'].Other"
* bodyQuestions.qcd3cc2c1 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcd3cc2c1')" "來源欄位／題目：BodyQuestions[Question='視力-部位']"
* bodyQuestions.qcd3cc2c1.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcd3cc2c1').item.where(linkId='BodyQuestions.qcd3cc2c1.Answer')" "來源欄位／題目：BodyQuestions[Question='視力-部位'].Answer"
* bodyQuestions.qcd3cc2c1.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcd3cc2c1').item.where(linkId='BodyQuestions.qcd3cc2c1.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='視力-部位'].MultipleAnswer"
* bodyQuestions.qcd3cc2c1.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcd3cc2c1').item.where(linkId='BodyQuestions.qcd3cc2c1.Other')" "來源欄位／題目：BodyQuestions[Question='視力-部位'].Other"
* bodyQuestions.q99290406 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q99290406')" "來源欄位／題目：BodyQuestions[Question='視力-影響日常活動']"
* bodyQuestions.q99290406.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q99290406').item.where(linkId='BodyQuestions.q99290406.Answer')" "來源欄位／題目：BodyQuestions[Question='視力-影響日常活動'].Answer"
* bodyQuestions.q99290406.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q99290406').item.where(linkId='BodyQuestions.q99290406.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='視力-影響日常活動'].MultipleAnswer"
* bodyQuestions.q99290406.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q99290406').item.where(linkId='BodyQuestions.q99290406.Other')" "來源欄位／題目：BodyQuestions[Question='視力-影響日常活動'].Other"
* bodyQuestions.q24eedc1b -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q24eedc1b')" "來源欄位／題目：BodyQuestions[Question='視力-輔具']"
* bodyQuestions.q24eedc1b.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q24eedc1b').item.where(linkId='BodyQuestions.q24eedc1b.Answer')" "來源欄位／題目：BodyQuestions[Question='視力-輔具'].Answer"
* bodyQuestions.q24eedc1b.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q24eedc1b').item.where(linkId='BodyQuestions.q24eedc1b.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='視力-輔具'].MultipleAnswer"
* bodyQuestions.q24eedc1b.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q24eedc1b').item.where(linkId='BodyQuestions.q24eedc1b.Other')" "來源欄位／題目：BodyQuestions[Question='視力-輔具'].Other"
* bodyQuestions.q6215056f -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6215056f')" "來源欄位／題目：BodyQuestions[Question='聽力']"
* bodyQuestions.q6215056f.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6215056f').item.where(linkId='BodyQuestions.q6215056f.Answer')" "來源欄位／題目：BodyQuestions[Question='聽力'].Answer"
* bodyQuestions.q6215056f.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6215056f').item.where(linkId='BodyQuestions.q6215056f.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='聽力'].MultipleAnswer"
* bodyQuestions.q6215056f.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6215056f').item.where(linkId='BodyQuestions.q6215056f.Other')" "來源欄位／題目：BodyQuestions[Question='聽力'].Other"
* bodyQuestions.q1678a5f1 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1678a5f1')" "來源欄位／題目：BodyQuestions[Question='聽力-部位']"
* bodyQuestions.q1678a5f1.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1678a5f1').item.where(linkId='BodyQuestions.q1678a5f1.Answer')" "來源欄位／題目：BodyQuestions[Question='聽力-部位'].Answer"
* bodyQuestions.q1678a5f1.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1678a5f1').item.where(linkId='BodyQuestions.q1678a5f1.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='聽力-部位'].MultipleAnswer"
* bodyQuestions.q1678a5f1.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1678a5f1').item.where(linkId='BodyQuestions.q1678a5f1.Other')" "來源欄位／題目：BodyQuestions[Question='聽力-部位'].Other"
* bodyQuestions.q93005aaa -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q93005aaa')" "來源欄位／題目：BodyQuestions[Question='聽力-影響日常活動']"
* bodyQuestions.q93005aaa.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q93005aaa').item.where(linkId='BodyQuestions.q93005aaa.Answer')" "來源欄位／題目：BodyQuestions[Question='聽力-影響日常活動'].Answer"
* bodyQuestions.q93005aaa.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q93005aaa').item.where(linkId='BodyQuestions.q93005aaa.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='聽力-影響日常活動'].MultipleAnswer"
* bodyQuestions.q93005aaa.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q93005aaa').item.where(linkId='BodyQuestions.q93005aaa.Other')" "來源欄位／題目：BodyQuestions[Question='聽力-影響日常活動'].Other"
* bodyQuestions.q2386d883 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q2386d883')" "來源欄位／題目：BodyQuestions[Question='聽力-輔具']"
* bodyQuestions.q2386d883.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q2386d883').item.where(linkId='BodyQuestions.q2386d883.Answer')" "來源欄位／題目：BodyQuestions[Question='聽力-輔具'].Answer"
* bodyQuestions.q2386d883.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q2386d883').item.where(linkId='BodyQuestions.q2386d883.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='聽力-輔具'].MultipleAnswer"
* bodyQuestions.q2386d883.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q2386d883').item.where(linkId='BodyQuestions.q2386d883.Other')" "來源欄位／題目：BodyQuestions[Question='聽力-輔具'].Other"
* bodyQuestions.q306e4676 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q306e4676')" "來源欄位／題目：BodyQuestions[Question='溝通']"
* bodyQuestions.q306e4676.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q306e4676').item.where(linkId='BodyQuestions.q306e4676.Answer')" "來源欄位／題目：BodyQuestions[Question='溝通'].Answer"
* bodyQuestions.q306e4676.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q306e4676').item.where(linkId='BodyQuestions.q306e4676.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='溝通'].MultipleAnswer"
* bodyQuestions.q306e4676.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q306e4676').item.where(linkId='BodyQuestions.q306e4676.Other')" "來源欄位／題目：BodyQuestions[Question='溝通'].Other"
* bodyQuestions.q63b2fbbe -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q63b2fbbe')" "來源欄位／題目：BodyQuestions[Question='溝通-影響日常活動']"
* bodyQuestions.q63b2fbbe.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q63b2fbbe').item.where(linkId='BodyQuestions.q63b2fbbe.Answer')" "來源欄位／題目：BodyQuestions[Question='溝通-影響日常活動'].Answer"
* bodyQuestions.q63b2fbbe.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q63b2fbbe').item.where(linkId='BodyQuestions.q63b2fbbe.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='溝通-影響日常活動'].MultipleAnswer"
* bodyQuestions.q63b2fbbe.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q63b2fbbe').item.where(linkId='BodyQuestions.q63b2fbbe.Other')" "來源欄位／題目：BodyQuestions[Question='溝通-影響日常活動'].Other"
* bodyQuestions.q3288f369 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3288f369')" "來源欄位／題目：BodyQuestions[Question='說話']"
* bodyQuestions.q3288f369.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3288f369').item.where(linkId='BodyQuestions.q3288f369.Answer')" "來源欄位／題目：BodyQuestions[Question='說話'].Answer"
* bodyQuestions.q3288f369.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3288f369').item.where(linkId='BodyQuestions.q3288f369.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='說話'].MultipleAnswer"
* bodyQuestions.q3288f369.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3288f369').item.where(linkId='BodyQuestions.q3288f369.Other')" "來源欄位／題目：BodyQuestions[Question='說話'].Other"
* bodyQuestions.q14304745 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q14304745')" "來源欄位／題目：BodyQuestions[Question='理解']"
* bodyQuestions.q14304745.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q14304745').item.where(linkId='BodyQuestions.q14304745.Answer')" "來源欄位／題目：BodyQuestions[Question='理解'].Answer"
* bodyQuestions.q14304745.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q14304745').item.where(linkId='BodyQuestions.q14304745.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='理解'].MultipleAnswer"
* bodyQuestions.q14304745.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q14304745').item.where(linkId='BodyQuestions.q14304745.Other')" "來源欄位／題目：BodyQuestions[Question='理解'].Other"
* bodyQuestions.q7ca654d9 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q7ca654d9')" "來源欄位／題目：BodyQuestions[Question='口腔外觀']"
* bodyQuestions.q7ca654d9.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q7ca654d9').item.where(linkId='BodyQuestions.q7ca654d9.Answer')" "來源欄位／題目：BodyQuestions[Question='口腔外觀'].Answer"
* bodyQuestions.q7ca654d9.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q7ca654d9').item.where(linkId='BodyQuestions.q7ca654d9.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='口腔外觀'].MultipleAnswer"
* bodyQuestions.q7ca654d9.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q7ca654d9').item.where(linkId='BodyQuestions.q7ca654d9.Other')" "來源欄位／題目：BodyQuestions[Question='口腔外觀'].Other"
* bodyQuestions.q53fb7d09 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q53fb7d09')" "來源欄位／題目：BodyQuestions[Question='特殊進食']"
* bodyQuestions.q53fb7d09.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q53fb7d09').item.where(linkId='BodyQuestions.q53fb7d09.Answer')" "來源欄位／題目：BodyQuestions[Question='特殊進食'].Answer"
* bodyQuestions.q53fb7d09.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q53fb7d09').item.where(linkId='BodyQuestions.q53fb7d09.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='特殊進食'].MultipleAnswer"
* bodyQuestions.q53fb7d09.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q53fb7d09').item.where(linkId='BodyQuestions.q53fb7d09.Other')" "來源欄位／題目：BodyQuestions[Question='特殊進食'].Other"
* bodyQuestions.qfcd3bd60 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfcd3bd60')" "來源欄位／題目：BodyQuestions[Question='假牙狀況']"
* bodyQuestions.qfcd3bd60.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfcd3bd60').item.where(linkId='BodyQuestions.qfcd3bd60.Answer')" "來源欄位／題目：BodyQuestions[Question='假牙狀況'].Answer"
* bodyQuestions.qfcd3bd60.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfcd3bd60').item.where(linkId='BodyQuestions.qfcd3bd60.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='假牙狀況'].MultipleAnswer"
* bodyQuestions.qfcd3bd60.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfcd3bd60').item.where(linkId='BodyQuestions.qfcd3bd60.Other')" "來源欄位／題目：BodyQuestions[Question='假牙狀況'].Other"
* bodyQuestions.q7b3136eb -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q7b3136eb')" "來源欄位／題目：BodyQuestions[Question='腹部狀態']"
* bodyQuestions.q7b3136eb.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q7b3136eb').item.where(linkId='BodyQuestions.q7b3136eb.Answer')" "來源欄位／題目：BodyQuestions[Question='腹部狀態'].Answer"
* bodyQuestions.q7b3136eb.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q7b3136eb').item.where(linkId='BodyQuestions.q7b3136eb.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='腹部狀態'].MultipleAnswer"
* bodyQuestions.q7b3136eb.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q7b3136eb').item.where(linkId='BodyQuestions.q7b3136eb.Other')" "來源欄位／題目：BodyQuestions[Question='腹部狀態'].Other"
* bodyQuestions.qc0a49d43 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qc0a49d43')" "來源欄位／題目：BodyQuestions[Question='腸蠕動']"
* bodyQuestions.qc0a49d43.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qc0a49d43').item.where(linkId='BodyQuestions.qc0a49d43.Answer')" "來源欄位／題目：BodyQuestions[Question='腸蠕動'].Answer"
* bodyQuestions.qc0a49d43.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qc0a49d43').item.where(linkId='BodyQuestions.qc0a49d43.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='腸蠕動'].MultipleAnswer"
* bodyQuestions.qc0a49d43.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qc0a49d43').item.where(linkId='BodyQuestions.qc0a49d43.Other')" "來源欄位／題目：BodyQuestions[Question='腸蠕動'].Other"
* bodyQuestions.qd49ab702 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd49ab702')" "來源欄位／題目：BodyQuestions[Question='消化狀態']"
* bodyQuestions.qd49ab702.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd49ab702').item.where(linkId='BodyQuestions.qd49ab702.Answer')" "來源欄位／題目：BodyQuestions[Question='消化狀態'].Answer"
* bodyQuestions.qd49ab702.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd49ab702').item.where(linkId='BodyQuestions.qd49ab702.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='消化狀態'].MultipleAnswer"
* bodyQuestions.qd49ab702.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd49ab702').item.where(linkId='BodyQuestions.qd49ab702.Other')" "來源欄位／題目：BodyQuestions[Question='消化狀態'].Other"
* bodyQuestions.q1b2dc66c -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1b2dc66c')" "來源欄位／題目：BodyQuestions[Question='排便型態']"
* bodyQuestions.q1b2dc66c.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1b2dc66c').item.where(linkId='BodyQuestions.q1b2dc66c.Answer')" "來源欄位／題目：BodyQuestions[Question='排便型態'].Answer"
* bodyQuestions.q1b2dc66c.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1b2dc66c').item.where(linkId='BodyQuestions.q1b2dc66c.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='排便型態'].MultipleAnswer"
* bodyQuestions.q1b2dc66c.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1b2dc66c').item.where(linkId='BodyQuestions.q1b2dc66c.Other')" "來源欄位／題目：BodyQuestions[Question='排便型態'].Other"
* bodyQuestions.qfaaaf47f -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfaaaf47f')" "來源欄位／題目：BodyQuestions[Question='排便顏色']"
* bodyQuestions.qfaaaf47f.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfaaaf47f').item.where(linkId='BodyQuestions.qfaaaf47f.Answer')" "來源欄位／題目：BodyQuestions[Question='排便顏色'].Answer"
* bodyQuestions.qfaaaf47f.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfaaaf47f').item.where(linkId='BodyQuestions.qfaaaf47f.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='排便顏色'].MultipleAnswer"
* bodyQuestions.qfaaaf47f.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfaaaf47f').item.where(linkId='BodyQuestions.qfaaaf47f.Other')" "來源欄位／題目：BodyQuestions[Question='排便顏色'].Other"
* bodyQuestions.qbfd21c82 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qbfd21c82')" "來源欄位／題目：BodyQuestions[Question='排便輔助']"
* bodyQuestions.qbfd21c82.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qbfd21c82').item.where(linkId='BodyQuestions.qbfd21c82.Answer')" "來源欄位／題目：BodyQuestions[Question='排便輔助'].Answer"
* bodyQuestions.qbfd21c82.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qbfd21c82').item.where(linkId='BodyQuestions.qbfd21c82.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='排便輔助'].MultipleAnswer"
* bodyQuestions.qbfd21c82.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qbfd21c82').item.where(linkId='BodyQuestions.qbfd21c82.Other')" "來源欄位／題目：BodyQuestions[Question='排便輔助'].Other"
* bodyQuestions.q0cdace56 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q0cdace56')" "來源欄位／題目：BodyQuestions[Question='排尿型態']"
* bodyQuestions.q0cdace56.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q0cdace56').item.where(linkId='BodyQuestions.q0cdace56.Answer')" "來源欄位／題目：BodyQuestions[Question='排尿型態'].Answer"
* bodyQuestions.q0cdace56.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q0cdace56').item.where(linkId='BodyQuestions.q0cdace56.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='排尿型態'].MultipleAnswer"
* bodyQuestions.q0cdace56.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q0cdace56').item.where(linkId='BodyQuestions.q0cdace56.Other')" "來源欄位／題目：BodyQuestions[Question='排尿型態'].Other"
* bodyQuestions.q3170f977 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3170f977')" "來源欄位／題目：BodyQuestions[Question='排尿顏色']"
* bodyQuestions.q3170f977.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3170f977').item.where(linkId='BodyQuestions.q3170f977.Answer')" "來源欄位／題目：BodyQuestions[Question='排尿顏色'].Answer"
* bodyQuestions.q3170f977.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3170f977').item.where(linkId='BodyQuestions.q3170f977.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='排尿顏色'].MultipleAnswer"
* bodyQuestions.q3170f977.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3170f977').item.where(linkId='BodyQuestions.q3170f977.Other')" "來源欄位／題目：BodyQuestions[Question='排尿顏色'].Other"
* bodyQuestions.q1dddcc0f -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1dddcc0f')" "來源欄位／題目：BodyQuestions[Question='排尿輔助']"
* bodyQuestions.q1dddcc0f.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1dddcc0f').item.where(linkId='BodyQuestions.q1dddcc0f.Answer')" "來源欄位／題目：BodyQuestions[Question='排尿輔助'].Answer"
* bodyQuestions.q1dddcc0f.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1dddcc0f').item.where(linkId='BodyQuestions.q1dddcc0f.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='排尿輔助'].MultipleAnswer"
* bodyQuestions.q1dddcc0f.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1dddcc0f').item.where(linkId='BodyQuestions.q1dddcc0f.Other')" "來源欄位／題目：BodyQuestions[Question='排尿輔助'].Other"
* bodyQuestions.q889a3f5d -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q889a3f5d')" "來源欄位／題目：BodyQuestions[Question='溫度']"
* bodyQuestions.q889a3f5d.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q889a3f5d').item.where(linkId='BodyQuestions.q889a3f5d.Answer')" "來源欄位／題目：BodyQuestions[Question='溫度'].Answer"
* bodyQuestions.q889a3f5d.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q889a3f5d').item.where(linkId='BodyQuestions.q889a3f5d.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='溫度'].MultipleAnswer"
* bodyQuestions.q889a3f5d.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q889a3f5d').item.where(linkId='BodyQuestions.q889a3f5d.Other')" "來源欄位／題目：BodyQuestions[Question='溫度'].Other"
* bodyQuestions.qfbbbe51d -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfbbbe51d')" "來源欄位／題目：BodyQuestions[Question='濕度']"
* bodyQuestions.qfbbbe51d.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfbbbe51d').item.where(linkId='BodyQuestions.qfbbbe51d.Answer')" "來源欄位／題目：BodyQuestions[Question='濕度'].Answer"
* bodyQuestions.qfbbbe51d.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfbbbe51d').item.where(linkId='BodyQuestions.qfbbbe51d.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='濕度'].MultipleAnswer"
* bodyQuestions.qfbbbe51d.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qfbbbe51d').item.where(linkId='BodyQuestions.qfbbbe51d.Other')" "來源欄位／題目：BodyQuestions[Question='濕度'].Other"
* bodyQuestions.q2edc1f98 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q2edc1f98')" "來源欄位／題目：BodyQuestions[Question='顏色']"
* bodyQuestions.q2edc1f98.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q2edc1f98').item.where(linkId='BodyQuestions.q2edc1f98.Answer')" "來源欄位／題目：BodyQuestions[Question='顏色'].Answer"
* bodyQuestions.q2edc1f98.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q2edc1f98').item.where(linkId='BodyQuestions.q2edc1f98.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='顏色'].MultipleAnswer"
* bodyQuestions.q2edc1f98.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q2edc1f98').item.where(linkId='BodyQuestions.q2edc1f98.Other')" "來源欄位／題目：BodyQuestions[Question='顏色'].Other"
* bodyQuestions.q0aec089c -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q0aec089c')" "來源欄位／題目：BodyQuestions[Question='水腫級數']"
* bodyQuestions.q0aec089c.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q0aec089c').item.where(linkId='BodyQuestions.q0aec089c.Answer')" "來源欄位／題目：BodyQuestions[Question='水腫級數'].Answer"
* bodyQuestions.q0aec089c.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q0aec089c').item.where(linkId='BodyQuestions.q0aec089c.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='水腫級數'].MultipleAnswer"
* bodyQuestions.q0aec089c.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q0aec089c').item.where(linkId='BodyQuestions.q0aec089c.Other')" "來源欄位／題目：BodyQuestions[Question='水腫級數'].Other"
* bodyQuestions.q5b3534e0 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q5b3534e0')" "來源欄位／題目：BodyQuestions[Question='水腫等級']"
* bodyQuestions.q5b3534e0.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q5b3534e0').item.where(linkId='BodyQuestions.q5b3534e0.Answer')" "來源欄位／題目：BodyQuestions[Question='水腫等級'].Answer"
* bodyQuestions.q5b3534e0.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q5b3534e0').item.where(linkId='BodyQuestions.q5b3534e0.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='水腫等級'].MultipleAnswer"
* bodyQuestions.q5b3534e0.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q5b3534e0').item.where(linkId='BodyQuestions.q5b3534e0.Other')" "來源欄位／題目：BodyQuestions[Question='水腫等級'].Other"
* bodyQuestions.q6e6e5811 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6e6e5811')" "來源欄位／題目：BodyQuestions[Question='完整']"
* bodyQuestions.q6e6e5811.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6e6e5811').item.where(linkId='BodyQuestions.q6e6e5811.Answer')" "來源欄位／題目：BodyQuestions[Question='完整'].Answer"
* bodyQuestions.q6e6e5811.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6e6e5811').item.where(linkId='BodyQuestions.q6e6e5811.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='完整'].MultipleAnswer"
* bodyQuestions.q6e6e5811.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6e6e5811').item.where(linkId='BodyQuestions.q6e6e5811.Other')" "來源欄位／題目：BodyQuestions[Question='完整'].Other"
* bodyQuestions.q4c713f60 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q4c713f60')" "來源欄位／題目：BodyQuestions[Question='左上肢']"
* bodyQuestions.q4c713f60.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q4c713f60').item.where(linkId='BodyQuestions.q4c713f60.Answer')" "來源欄位／題目：BodyQuestions[Question='左上肢'].Answer"
* bodyQuestions.q4c713f60.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q4c713f60').item.where(linkId='BodyQuestions.q4c713f60.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='左上肢'].MultipleAnswer"
* bodyQuestions.q4c713f60.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q4c713f60').item.where(linkId='BodyQuestions.q4c713f60.Other')" "來源欄位／題目：BodyQuestions[Question='左上肢'].Other"
* bodyQuestions.q43c26e48 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q43c26e48')" "來源欄位／題目：BodyQuestions[Question='右上肢']"
* bodyQuestions.q43c26e48.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q43c26e48').item.where(linkId='BodyQuestions.q43c26e48.Answer')" "來源欄位／題目：BodyQuestions[Question='右上肢'].Answer"
* bodyQuestions.q43c26e48.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q43c26e48').item.where(linkId='BodyQuestions.q43c26e48.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='右上肢'].MultipleAnswer"
* bodyQuestions.q43c26e48.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q43c26e48').item.where(linkId='BodyQuestions.q43c26e48.Other')" "來源欄位／題目：BodyQuestions[Question='右上肢'].Other"
* bodyQuestions.q9926c640 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q9926c640')" "來源欄位／題目：BodyQuestions[Question='左下肢']"
* bodyQuestions.q9926c640.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q9926c640').item.where(linkId='BodyQuestions.q9926c640.Answer')" "來源欄位／題目：BodyQuestions[Question='左下肢'].Answer"
* bodyQuestions.q9926c640.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q9926c640').item.where(linkId='BodyQuestions.q9926c640.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='左下肢'].MultipleAnswer"
* bodyQuestions.q9926c640.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q9926c640').item.where(linkId='BodyQuestions.q9926c640.Other')" "來源欄位／題目：BodyQuestions[Question='左下肢'].Other"
* bodyQuestions.q3f44d138 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3f44d138')" "來源欄位／題目：BodyQuestions[Question='右下肢']"
* bodyQuestions.q3f44d138.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3f44d138').item.where(linkId='BodyQuestions.q3f44d138.Answer')" "來源欄位／題目：BodyQuestions[Question='右下肢'].Answer"
* bodyQuestions.q3f44d138.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3f44d138').item.where(linkId='BodyQuestions.q3f44d138.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='右下肢'].MultipleAnswer"
* bodyQuestions.q3f44d138.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3f44d138').item.where(linkId='BodyQuestions.q3f44d138.Other')" "來源欄位／題目：BodyQuestions[Question='右下肢'].Other"
* bodyQuestions.qcd675f81 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcd675f81')" "來源欄位／題目：BodyQuestions[Question='行動能力問題']"
* bodyQuestions.qcd675f81.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcd675f81').item.where(linkId='BodyQuestions.qcd675f81.Answer')" "來源欄位／題目：BodyQuestions[Question='行動能力問題'].Answer"
* bodyQuestions.qcd675f81.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcd675f81').item.where(linkId='BodyQuestions.qcd675f81.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='行動能力問題'].MultipleAnswer"
* bodyQuestions.qcd675f81.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcd675f81').item.where(linkId='BodyQuestions.qcd675f81.Other')" "來源欄位／題目：BodyQuestions[Question='行動能力問題'].Other"
* bodyQuestions.q3adf788d -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3adf788d')" "來源欄位／題目：BodyQuestions[Question='肌力-輔具']"
* bodyQuestions.q3adf788d.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3adf788d').item.where(linkId='BodyQuestions.q3adf788d.Answer')" "來源欄位／題目：BodyQuestions[Question='肌力-輔具'].Answer"
* bodyQuestions.q3adf788d.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3adf788d').item.where(linkId='BodyQuestions.q3adf788d.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='肌力-輔具'].MultipleAnswer"
* bodyQuestions.q3adf788d.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q3adf788d').item.where(linkId='BodyQuestions.q3adf788d.Other')" "來源欄位／題目：BodyQuestions[Question='肌力-輔具'].Other"
* bodyQuestions.q4ce17519 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q4ce17519')" "來源欄位／題目：BodyQuestions[Question='跌倒']"
* bodyQuestions.q4ce17519.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q4ce17519').item.where(linkId='BodyQuestions.q4ce17519.Answer')" "來源欄位／題目：BodyQuestions[Question='跌倒'].Answer"
* bodyQuestions.q4ce17519.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q4ce17519').item.where(linkId='BodyQuestions.q4ce17519.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='跌倒'].MultipleAnswer"
* bodyQuestions.q4ce17519.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q4ce17519').item.where(linkId='BodyQuestions.q4ce17519.Other')" "來源欄位／題目：BodyQuestions[Question='跌倒'].Other"
* bodyQuestions.qcc99d785 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcc99d785')" "來源欄位／題目：BodyQuestions[Question='跌倒次數']"
* bodyQuestions.qcc99d785.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcc99d785').item.where(linkId='BodyQuestions.qcc99d785.Answer')" "來源欄位／題目：BodyQuestions[Question='跌倒次數'].Answer"
* bodyQuestions.qcc99d785.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcc99d785').item.where(linkId='BodyQuestions.qcc99d785.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='跌倒次數'].MultipleAnswer"
* bodyQuestions.qcc99d785.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qcc99d785').item.where(linkId='BodyQuestions.qcc99d785.Other')" "來源欄位／題目：BodyQuestions[Question='跌倒次數'].Other"
* bodyQuestions.q1ea67d8d -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1ea67d8d')" "來源欄位／題目：BodyQuestions[Question='行為']"
* bodyQuestions.q1ea67d8d.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1ea67d8d').item.where(linkId='BodyQuestions.q1ea67d8d.Answer')" "來源欄位／題目：BodyQuestions[Question='行為'].Answer"
* bodyQuestions.q1ea67d8d.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1ea67d8d').item.where(linkId='BodyQuestions.q1ea67d8d.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='行為'].MultipleAnswer"
* bodyQuestions.q1ea67d8d.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1ea67d8d').item.where(linkId='BodyQuestions.q1ea67d8d.Other')" "來源欄位／題目：BodyQuestions[Question='行為'].Other"
* bodyQuestions.qca5f735b -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qca5f735b')" "來源欄位／題目：BodyQuestions[Question='睡眠']"
* bodyQuestions.qca5f735b.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qca5f735b').item.where(linkId='BodyQuestions.qca5f735b.Answer')" "來源欄位／題目：BodyQuestions[Question='睡眠'].Answer"
* bodyQuestions.qca5f735b.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qca5f735b').item.where(linkId='BodyQuestions.qca5f735b.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='睡眠'].MultipleAnswer"
* bodyQuestions.qca5f735b.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qca5f735b').item.where(linkId='BodyQuestions.qca5f735b.Other')" "來源欄位／題目：BodyQuestions[Question='睡眠'].Other"
* bodyQuestions.qd8db9643 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd8db9643')" "來源欄位／題目：BodyQuestions[Question='服用藥物']"
* bodyQuestions.qd8db9643.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd8db9643').item.where(linkId='BodyQuestions.qd8db9643.Answer')" "來源欄位／題目：BodyQuestions[Question='服用藥物'].Answer"
* bodyQuestions.qd8db9643.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd8db9643').item.where(linkId='BodyQuestions.qd8db9643.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='服用藥物'].MultipleAnswer"
* bodyQuestions.qd8db9643.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd8db9643').item.where(linkId='BodyQuestions.qd8db9643.Other')" "來源欄位／題目：BodyQuestions[Question='服用藥物'].Other"
* bodyQuestions.q65b57fd8 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q65b57fd8')" "來源欄位／題目：BodyQuestions[Question='藥物類別']"
* bodyQuestions.q65b57fd8.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q65b57fd8').item.where(linkId='BodyQuestions.q65b57fd8.Answer')" "來源欄位／題目：BodyQuestions[Question='藥物類別'].Answer"
* bodyQuestions.q65b57fd8.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q65b57fd8').item.where(linkId='BodyQuestions.q65b57fd8.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='藥物類別'].MultipleAnswer"
* bodyQuestions.q65b57fd8.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q65b57fd8').item.where(linkId='BodyQuestions.q65b57fd8.Other')" "來源欄位／題目：BodyQuestions[Question='藥物類別'].Other"
* bodyQuestions.q03fdb3f1 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q03fdb3f1')" "來源欄位／題目：BodyQuestions[Question='服用頻率']"
* bodyQuestions.q03fdb3f1.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q03fdb3f1').item.where(linkId='BodyQuestions.q03fdb3f1.Answer')" "來源欄位／題目：BodyQuestions[Question='服用頻率'].Answer"
* bodyQuestions.q03fdb3f1.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q03fdb3f1').item.where(linkId='BodyQuestions.q03fdb3f1.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='服用頻率'].MultipleAnswer"
* bodyQuestions.q03fdb3f1.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q03fdb3f1').item.where(linkId='BodyQuestions.q03fdb3f1.Other')" "來源欄位／題目：BodyQuestions[Question='服用頻率'].Other"
* bodyQuestions.qd30f4212 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd30f4212')" "來源欄位／題目：BodyQuestions[Question='輔助器']"
* bodyQuestions.qd30f4212.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd30f4212').item.where(linkId='BodyQuestions.qd30f4212.Answer')" "來源欄位／題目：BodyQuestions[Question='輔助器'].Answer"
* bodyQuestions.qd30f4212.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd30f4212').item.where(linkId='BodyQuestions.qd30f4212.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='輔助器'].MultipleAnswer"
* bodyQuestions.qd30f4212.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.qd30f4212').item.where(linkId='BodyQuestions.qd30f4212.Other')" "來源欄位／題目：BodyQuestions[Question='輔助器'].Other"
* bodyQuestions.q1355f181 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1355f181')" "來源欄位／題目：BodyQuestions[Question='有輔助器']"
* bodyQuestions.q1355f181.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1355f181').item.where(linkId='BodyQuestions.q1355f181.Answer')" "來源欄位／題目：BodyQuestions[Question='有輔助器'].Answer"
* bodyQuestions.q1355f181.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1355f181').item.where(linkId='BodyQuestions.q1355f181.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='有輔助器'].MultipleAnswer"
* bodyQuestions.q1355f181.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1355f181').item.where(linkId='BodyQuestions.q1355f181.Other')" "來源欄位／題目：BodyQuestions[Question='有輔助器'].Other"
* bodyQuestions.q1c902f78 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1c902f78')" "來源欄位／題目：BodyQuestions[Question='鼻導管']"
* bodyQuestions.q1c902f78.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1c902f78').item.where(linkId='BodyQuestions.q1c902f78.Answer')" "來源欄位／題目：BodyQuestions[Question='鼻導管'].Answer"
* bodyQuestions.q1c902f78.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1c902f78').item.where(linkId='BodyQuestions.q1c902f78.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='鼻導管'].MultipleAnswer"
* bodyQuestions.q1c902f78.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q1c902f78').item.where(linkId='BodyQuestions.q1c902f78.Other')" "來源欄位／題目：BodyQuestions[Question='鼻導管'].Other"
* bodyQuestions.q6772dc09 -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6772dc09')" "來源欄位／題目：BodyQuestions[Question='氧氣面罩']"
* bodyQuestions.q6772dc09.answer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6772dc09').item.where(linkId='BodyQuestions.q6772dc09.Answer')" "來源欄位／題目：BodyQuestions[Question='氧氣面罩'].Answer"
* bodyQuestions.q6772dc09.multipleAnswer -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6772dc09').item.where(linkId='BodyQuestions.q6772dc09.MultipleAnswer')" "來源欄位／題目：BodyQuestions[Question='氧氣面罩'].MultipleAnswer"
* bodyQuestions.q6772dc09.other -> "QuestionnaireResponse.item.where(linkId='BodyQuestions').item.where(linkId='BodyQuestions.q6772dc09').item.where(linkId='BodyQuestions.q6772dc09.Other')" "來源欄位／題目：BodyQuestions[Question='氧氣面罩'].Other"
* isTemporary -> "QuestionnaireResponse.item.where(linkId='IsTemporary')" "來源欄位／題目：IsTemporary"
