Logical: HNMedicalHistoriesModel
Id: HNMedicalHistoriesModel
Title: "居家護理－疾病史評估邏輯模型"
Description: "描述居家護理疾病史評估的資料需求。依 V5.0.16 有效欄位建立，來源欄位對應另列於 Mapping。"
* ^status = #draft
* ^version = "5.0.16"
* date 1..1 date "紀錄日期" "紀錄日期"
* nurseID 1..1 string "護理人員身分證字號" "護理人員身分證字號"
* ansOther1 1..1 string "主要診斷" "主要診斷"
* ansOther2 0..1 string "次要診斷" "次要診斷"
* medicalHistoryQuestions 1..1 BackboneElement "評估項目" "評估項目"
* medicalHistoryQuestions.q32e5fad7 1..1 BackboneElement "心臟問題(只包含心臟)" "心臟問題(只包含心臟)"
* medicalHistoryQuestions.q32e5fad7.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.q32e5fad7.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.q32e5fad7.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.qbeda0dd8 1..1 BackboneElement "周邊血管系統問題(包括高血壓)" "周邊血管系統問題(包括高血壓)"
* medicalHistoryQuestions.qbeda0dd8.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.qbeda0dd8.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.qbeda0dd8.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.q628b2adc 1..1 BackboneElement "造血系統問題(貧血、血球、淋巴、骨髓、脾臟等)" "造血系統問題(貧血、血球、淋巴、骨髓、脾臟等)"
* medicalHistoryQuestions.q628b2adc.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.q628b2adc.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.q628b2adc.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.q7e61f4f9 1..1 BackboneElement "呼吸系統問題(肺部、支氣管、氣管及抽菸狀況)" "呼吸系統問題(肺部、支氣管、氣管及抽菸狀況)"
* medicalHistoryQuestions.q7e61f4f9.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.q7e61f4f9.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.q7e61f4f9.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.q958e3479 1..1 BackboneElement "眼耳鼻喉問題" "眼耳鼻喉問題"
* medicalHistoryQuestions.q958e3479.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.q958e3479.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.q958e3479.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.q5713fd48 1..1 BackboneElement "上消化道問題(食道、胃、十二指腸)" "上消化道問題(食道、胃、十二指腸)"
* medicalHistoryQuestions.q5713fd48.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.q5713fd48.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.q5713fd48.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.q486b7939 1..1 BackboneElement "下消化道問題(小腸、大腸、直腸)" "下消化道問題(小腸、大腸、直腸)"
* medicalHistoryQuestions.q486b7939.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.q486b7939.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.q486b7939.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.qb7ad0283 1..1 BackboneElement "肝膽胰臟問題" "肝膽胰臟問題"
* medicalHistoryQuestions.qb7ad0283.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.qb7ad0283.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.qb7ad0283.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.qc62d7017 1..1 BackboneElement "腎臟問題" "腎臟問題"
* medicalHistoryQuestions.qc62d7017.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.qc62d7017.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.qc62d7017.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.qa92ba1d3 1..1 BackboneElement "其他泌尿生殖系統問題(輸尿管、尿道、膀胱、攝護腺、其他生殖系統問題)" "其他泌尿生殖系統問題(輸尿管、尿道、膀胱、攝護腺、其他生殖系統問題)"
* medicalHistoryQuestions.qa92ba1d3.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.qa92ba1d3.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.qa92ba1d3.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.q48138ed7 1..1 BackboneElement "肌肉骨骼皮膚問題" "肌肉骨骼皮膚問題"
* medicalHistoryQuestions.q48138ed7.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.q48138ed7.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.q48138ed7.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.q24f8809f 1..1 BackboneElement "神經系統問題(腦部、脊髓、周邊神經等、不包含失智症)" "神經系統問題(腦部、脊髓、周邊神經等、不包含失智症)"
* medicalHistoryQuestions.q24f8809f.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.q24f8809f.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.q24f8809f.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.qe34cc85c 1..1 BackboneElement "內分泌、感染與代謝問題(包含糖尿病、甲狀腺、肥胖、乳房異常、感染性疾病與毒藥物問題)" "內分泌、感染與代謝問題(包含糖尿病、甲狀腺、肥胖、乳房異常、感染性疾病與毒藥物問題)"
* medicalHistoryQuestions.qe34cc85c.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.qe34cc85c.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.qe34cc85c.statement 0..1 string "備註" "備註"
* medicalHistoryQuestions.q2c808271 1..1 BackboneElement "情緒與行為問題(包括憂鬱、焦慮、激躁、急性混亂、瞻妄及失智症等問題)" "情緒與行為問題(包括憂鬱、焦慮、激躁、急性混亂、瞻妄及失智症等問題)"
* medicalHistoryQuestions.q2c808271.answer 1..1 Coding "評估答案" "評估答案"
* medicalHistoryQuestions.q2c808271.answer from hn-vs-d782d810cfdd (required)
* medicalHistoryQuestions.q2c808271.statement 0..1 string "備註" "備註"
* isTemporary 0..1 Coding "是否暫存" "是否暫存"
* isTemporary from hn-vs-58e4d598f859 (required)

Mapping: HNMedicalHistoriesModelToFHIR
Id: hn-medicalhistories-fhir
Title: "居家護理－疾病史評估欄位對應"
Source: HNMedicalHistoriesModel
Target: "http://ltc-ig.fhir.tw/StructureDefinition/HNMedicalHistoriesResponse"
* date -> "QuestionnaireResponse.item.where(linkId='Date')" "來源欄位／題目：Date"
* nurseID -> "QuestionnaireResponse.item.where(linkId='NurseID')" "來源欄位／題目：NurseID"
* ansOther1 -> "QuestionnaireResponse.item.where(linkId='AnsOther_1')" "來源欄位／題目：AnsOther_1"
* ansOther2 -> "QuestionnaireResponse.item.where(linkId='AnsOther_2')" "來源欄位／題目：AnsOther_2"
* medicalHistoryQuestions -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions')" "來源欄位／題目：MedicalHistoryQuestions"
* medicalHistoryQuestions.q32e5fad7 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q32e5fad7')" "來源欄位／題目：MedicalHistoryQuestions[Question='心臟問題(只包含心臟)']"
* medicalHistoryQuestions.q32e5fad7.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q32e5fad7').item.where(linkId='MedicalHistoryQuestions.q32e5fad7.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='心臟問題(只包含心臟)'].Answer"
* medicalHistoryQuestions.q32e5fad7.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q32e5fad7').item.where(linkId='MedicalHistoryQuestions.q32e5fad7.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='心臟問題(只包含心臟)'].Statement"
* medicalHistoryQuestions.qbeda0dd8 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qbeda0dd8')" "來源欄位／題目：MedicalHistoryQuestions[Question='周邊血管系統問題(包括高血壓)']"
* medicalHistoryQuestions.qbeda0dd8.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qbeda0dd8').item.where(linkId='MedicalHistoryQuestions.qbeda0dd8.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='周邊血管系統問題(包括高血壓)'].Answer"
* medicalHistoryQuestions.qbeda0dd8.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qbeda0dd8').item.where(linkId='MedicalHistoryQuestions.qbeda0dd8.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='周邊血管系統問題(包括高血壓)'].Statement"
* medicalHistoryQuestions.q628b2adc -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q628b2adc')" "來源欄位／題目：MedicalHistoryQuestions[Question='造血系統問題(貧血、血球、淋巴、骨髓、脾臟等)']"
* medicalHistoryQuestions.q628b2adc.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q628b2adc').item.where(linkId='MedicalHistoryQuestions.q628b2adc.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='造血系統問題(貧血、血球、淋巴、骨髓、脾臟等)'].Answer"
* medicalHistoryQuestions.q628b2adc.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q628b2adc').item.where(linkId='MedicalHistoryQuestions.q628b2adc.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='造血系統問題(貧血、血球、淋巴、骨髓、脾臟等)'].Statement"
* medicalHistoryQuestions.q7e61f4f9 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q7e61f4f9')" "來源欄位／題目：MedicalHistoryQuestions[Question='呼吸系統問題(肺部、支氣管、氣管及抽菸狀況)']"
* medicalHistoryQuestions.q7e61f4f9.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q7e61f4f9').item.where(linkId='MedicalHistoryQuestions.q7e61f4f9.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='呼吸系統問題(肺部、支氣管、氣管及抽菸狀況)'].Answer"
* medicalHistoryQuestions.q7e61f4f9.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q7e61f4f9').item.where(linkId='MedicalHistoryQuestions.q7e61f4f9.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='呼吸系統問題(肺部、支氣管、氣管及抽菸狀況)'].Statement"
* medicalHistoryQuestions.q958e3479 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q958e3479')" "來源欄位／題目：MedicalHistoryQuestions[Question='眼耳鼻喉問題']"
* medicalHistoryQuestions.q958e3479.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q958e3479').item.where(linkId='MedicalHistoryQuestions.q958e3479.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='眼耳鼻喉問題'].Answer"
* medicalHistoryQuestions.q958e3479.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q958e3479').item.where(linkId='MedicalHistoryQuestions.q958e3479.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='眼耳鼻喉問題'].Statement"
* medicalHistoryQuestions.q5713fd48 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q5713fd48')" "來源欄位／題目：MedicalHistoryQuestions[Question='上消化道問題(食道、胃、十二指腸)']"
* medicalHistoryQuestions.q5713fd48.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q5713fd48').item.where(linkId='MedicalHistoryQuestions.q5713fd48.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='上消化道問題(食道、胃、十二指腸)'].Answer"
* medicalHistoryQuestions.q5713fd48.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q5713fd48').item.where(linkId='MedicalHistoryQuestions.q5713fd48.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='上消化道問題(食道、胃、十二指腸)'].Statement"
* medicalHistoryQuestions.q486b7939 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q486b7939')" "來源欄位／題目：MedicalHistoryQuestions[Question='下消化道問題(小腸、大腸、直腸)']"
* medicalHistoryQuestions.q486b7939.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q486b7939').item.where(linkId='MedicalHistoryQuestions.q486b7939.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='下消化道問題(小腸、大腸、直腸)'].Answer"
* medicalHistoryQuestions.q486b7939.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q486b7939').item.where(linkId='MedicalHistoryQuestions.q486b7939.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='下消化道問題(小腸、大腸、直腸)'].Statement"
* medicalHistoryQuestions.qb7ad0283 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qb7ad0283')" "來源欄位／題目：MedicalHistoryQuestions[Question='肝膽胰臟問題']"
* medicalHistoryQuestions.qb7ad0283.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qb7ad0283').item.where(linkId='MedicalHistoryQuestions.qb7ad0283.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='肝膽胰臟問題'].Answer"
* medicalHistoryQuestions.qb7ad0283.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qb7ad0283').item.where(linkId='MedicalHistoryQuestions.qb7ad0283.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='肝膽胰臟問題'].Statement"
* medicalHistoryQuestions.qc62d7017 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qc62d7017')" "來源欄位／題目：MedicalHistoryQuestions[Question='腎臟問題']"
* medicalHistoryQuestions.qc62d7017.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qc62d7017').item.where(linkId='MedicalHistoryQuestions.qc62d7017.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='腎臟問題'].Answer"
* medicalHistoryQuestions.qc62d7017.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qc62d7017').item.where(linkId='MedicalHistoryQuestions.qc62d7017.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='腎臟問題'].Statement"
* medicalHistoryQuestions.qa92ba1d3 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qa92ba1d3')" "來源欄位／題目：MedicalHistoryQuestions[Question='其他泌尿生殖系統問題(輸尿管、尿道、膀胱、攝護腺、其他生殖系統問題)']"
* medicalHistoryQuestions.qa92ba1d3.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qa92ba1d3').item.where(linkId='MedicalHistoryQuestions.qa92ba1d3.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='其他泌尿生殖系統問題(輸尿管、尿道、膀胱、攝護腺、其他生殖系統問題)'].Answer"
* medicalHistoryQuestions.qa92ba1d3.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qa92ba1d3').item.where(linkId='MedicalHistoryQuestions.qa92ba1d3.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='其他泌尿生殖系統問題(輸尿管、尿道、膀胱、攝護腺、其他生殖系統問題)'].Statement"
* medicalHistoryQuestions.q48138ed7 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q48138ed7')" "來源欄位／題目：MedicalHistoryQuestions[Question='肌肉骨骼皮膚問題']"
* medicalHistoryQuestions.q48138ed7.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q48138ed7').item.where(linkId='MedicalHistoryQuestions.q48138ed7.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='肌肉骨骼皮膚問題'].Answer"
* medicalHistoryQuestions.q48138ed7.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q48138ed7').item.where(linkId='MedicalHistoryQuestions.q48138ed7.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='肌肉骨骼皮膚問題'].Statement"
* medicalHistoryQuestions.q24f8809f -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q24f8809f')" "來源欄位／題目：MedicalHistoryQuestions[Question='神經系統問題(腦部、脊髓、周邊神經等、不包含失智症)']"
* medicalHistoryQuestions.q24f8809f.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q24f8809f').item.where(linkId='MedicalHistoryQuestions.q24f8809f.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='神經系統問題(腦部、脊髓、周邊神經等、不包含失智症)'].Answer"
* medicalHistoryQuestions.q24f8809f.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q24f8809f').item.where(linkId='MedicalHistoryQuestions.q24f8809f.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='神經系統問題(腦部、脊髓、周邊神經等、不包含失智症)'].Statement"
* medicalHistoryQuestions.qe34cc85c -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qe34cc85c')" "來源欄位／題目：MedicalHistoryQuestions[Question='內分泌、感染與代謝問題(包含糖尿病、甲狀腺、肥胖、乳房異常、感染性疾病與毒藥物問題)']"
* medicalHistoryQuestions.qe34cc85c.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qe34cc85c').item.where(linkId='MedicalHistoryQuestions.qe34cc85c.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='內分泌、感染與代謝問題(包含糖尿病、甲狀腺、肥胖、乳房異常、感染性疾病與毒藥物問題)'].Answer"
* medicalHistoryQuestions.qe34cc85c.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.qe34cc85c').item.where(linkId='MedicalHistoryQuestions.qe34cc85c.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='內分泌、感染與代謝問題(包含糖尿病、甲狀腺、肥胖、乳房異常、感染性疾病與毒藥物問題)'].Statement"
* medicalHistoryQuestions.q2c808271 -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q2c808271')" "來源欄位／題目：MedicalHistoryQuestions[Question='情緒與行為問題(包括憂鬱、焦慮、激躁、急性混亂、瞻妄及失智症等問題)']"
* medicalHistoryQuestions.q2c808271.answer -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q2c808271').item.where(linkId='MedicalHistoryQuestions.q2c808271.Answer')" "來源欄位／題目：MedicalHistoryQuestions[Question='情緒與行為問題(包括憂鬱、焦慮、激躁、急性混亂、瞻妄及失智症等問題)'].Answer"
* medicalHistoryQuestions.q2c808271.statement -> "QuestionnaireResponse.item.where(linkId='MedicalHistoryQuestions').item.where(linkId='MedicalHistoryQuestions.q2c808271').item.where(linkId='MedicalHistoryQuestions.q2c808271.Statement')" "來源欄位／題目：MedicalHistoryQuestions[Question='情緒與行為問題(包括憂鬱、焦慮、激躁、急性混亂、瞻妄及失智症等問題)'].Statement"
* isTemporary -> "QuestionnaireResponse.item.where(linkId='IsTemporary')" "來源欄位／題目：IsTemporary"
