Logical: HAHCareDataset
Parent: Element
Id: HAHCareDataset
Title: "在宅急症－照護資料集"
Description: "依在宅急症系統盤點建立的資料交換模型，涵蓋正式收案、訪視、照護、檢驗、給藥與轉銜。新增的臨床結構不代表來源系統已實作；來源差異見專用對照表。"
* ^status = #draft
* patient 1..1 BackboneElement "個案" "個案。[以下欄位為此項資料的內嵌元素。]"
* patient.identifier 1..* Identifier "個案識別碼" "個案識別碼。[填入識別碼系統與值；至少包含機構給予的個案識別碼。]"
* patient.name 1..2 HumanName "姓名" "姓名。[填入完整姓名；可另以 family 與 given 記錄姓和名。]"
* patient.birthDate 1..1 date "出生日期" "出生日期。[以 YYYY-MM-DD 格式填寫日期。]"
* patient.gender 0..1 code "性別" "性別。[填入所綁定值集允許的代碼。]"
* patient.address 1..2 Address "居住地址" "居住地址。[填入完整地址，可另記錄縣市、行政區及郵遞區號。]"
* patient.telecom 1..* ContactPoint "聯絡方式" "聯絡方式。[填入聯絡種類 system 與實際號碼或地址 value。]"
* patient.contact 1..* BackboneElement "緊急聯絡人" "緊急聯絡人。[以下欄位為此項資料的內嵌元素。]"
* patient.contact.name 1..1 HumanName "聯絡人姓名" "聯絡人姓名。[填入完整姓名；可另以 family 與 given 記錄姓和名。]"
* patient.contact.relationship 1..1 CodeableConcept "與個案關係" "與個案關係。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* patient.contact.telecom 1..* ContactPoint "聯絡人電話" "聯絡人電話。[填入聯絡種類 system 與實際號碼或地址 value。]"
* patient.caregiver 0..* Reference(LTCRelatedPerson) "主要照顧者" "主要照顧者。[應填入對應的 LTCRelatedPerson Reference。]"
* patient.deceased 0..1 dateTime "死亡時間" "死亡時間。[填入已確認的死亡時間；不從結案狀態推定。]"
* intake 0..1 BackboneElement "收案評估" "收案評估。[以下欄位為此項資料的內嵌元素。]"
* intake.criteria 1..1 string "計畫名稱與版本" "計畫名稱與版本。[填入本次評估適用的照護計畫名稱及版本。]"
* intake.homeSafety 1..1 string "環境與設備可行性" "環境與設備可行性。[描述供電、通訊、設備及居家環境是否可支援預定照護。]"
* intake.caregiverSupport 1..1 string "照顧者支援能力" "照顧者支援能力。[描述照顧者可提供的協助及尚需補足的能力。]"
* intake.decision 1..1 Coding "收案建議" "收案建議。[填入代碼系統 system 與代碼 code。]"
* intake.reason 0..1 string "評估原因" "評估原因。[評估為 pending 或 ineligible 時填入原因。]"
* intake.assessor 1..1 Reference(LTCPractitionerRole or LTCPractitioner) "評估人員" "評估人員。[應填入對應的 LTCPractitionerRole／LTCPractitioner Reference。]"
* intake.date 1..1 dateTime "評估時間" "評估時間。[填入實際時間；包含時分時須提供時區。]"
* episode 1..1 BackboneElement "一次收案療程" "一次收案療程。[以下欄位為此項資料的內嵌元素。]"
* episode.identifier 1..* Identifier "療程識別碼" "療程識別碼。[每次收案使用獨立識別碼，包含發碼系統與值。]"
* episode.status 1..1 code "療程狀態" "療程狀態。[填入所綁定值集允許的代碼。]"
* episode.period 1..1 Period "實際照護期間" "實際照護期間。[填入收案開始時間；完成療程時另填實際結束時間。]"
* episode.organization 1..1 Reference(LTCOrganization) "負責機構" "負責機構。[應填入對應的 LTCOrganization Reference。]"
* episode.diagnosis 0..* Reference(HAHCondition) "收案診斷" "收案診斷。[應填入對應的 HAHCondition Reference。]"
* episode.team 0..* Reference(HAHCareTeam) "照護團隊" "照護團隊。[應填入對應的 HAHCareTeam Reference。]"
* episode.referral 0..* Reference(HAHServiceRequest) "收案轉介" "收案轉介。[應填入對應的 HAHServiceRequest Reference。]"
* episode.outcome 0..1 CodeableConcept "結束原因" "結束原因。[完成療程時填寫；其他原因另填 text 說明。]"
* encounter 1..* BackboneElement "整段照護或單次訪視" "整段照護或單次訪視。[以下欄位為此項資料的內嵌元素。]"
* encounter.identifier 0..* Identifier "就診識別碼" "就診識別碼。[填入識別系統 system 與識別值 value。]"
* encounter.status 1..1 code "就診狀態" "就診狀態。[填入所綁定值集允許的代碼。]"
* encounter.class 1..1 Coding "照護分類" "照護分類。[整段照護填 IMP、實地訪視填 HH、遠距評估填 VR，使用 v3-ActCode。]"
* encounter.period 1..1 Period "實際服務起訖" "實際服務起訖。[使用 start、end 填入起訖時間；尚未結束時不預填實際結束時間。]"
* encounter.parent 0..1 Reference(HAHAdmissionEncounter) "所屬整段照護" "所屬整段照護。[單次訪視應參照本次整段照護的 Encounter。]"
* encounter.mode 0..1 code "訪視方式" "訪視方式。[單次訪視填入 in-person、video 或 telephone。]"
* encounter.participant 1..* Reference(LTCPractitioner or LTCPractitionerRole) "照護人員" "照護人員。[應填入對應的 LTCPractitioner／LTCPractitionerRole Reference。]"
* encounter.organization 1..1 Reference(LTCOrganization) "服務機構" "服務機構。[應填入對應的 LTCOrganization Reference。]"
* encounter.location 0..* Reference(Location) "照護地點" "照護地點。[應填入對應的 Location Reference。]"
* encounter.disposition 0..1 CodeableConcept "出院或轉出處置" "出院或轉出處置。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* encounter.destination 0..1 Reference(Organization or Location) "接續照護地點" "接續照護地點。[應填入對應的 Organization／Location Reference。]"
* problem 0..* BackboneElement "診斷與照護問題" "診斷與照護問題。[以下欄位為此項資料的內嵌元素。]"
* problem.code 1..1 CodeableConcept "診斷或問題" "診斷或問題。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* problem.category 1..1 CodeableConcept "診斷或問題分類" "診斷或問題分類。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* problem.onset 0..1 dateTime "發病時間" "發病時間。[填入實際時間；包含時分時須提供時區。]"
* problem.clinicalStatus 0..1 CodeableConcept "病情狀態" "病情狀態。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* problem.verification 0..1 CodeableConcept "確認狀態" "確認狀態。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* problem.encounter 1..1 Reference(HAHEncounter) "對應就診" "對應就診。[應填入對應的 HAHEncounter Reference。]"
* team 0..* BackboneElement "團隊成員" "團隊成員。[以下欄位為此項資料的內嵌元素。]"
* team.member 1..1 Reference(Practitioner or PractitionerRole or Organization or RelatedPerson) "人員或機構" "人員或機構。[應填入對應的 Practitioner／PractitionerRole／Organization／RelatedPerson Reference。]"
* team.role 1..1 CodeableConcept "成員角色" "成員角色。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* team.period 0..1 Period "責任期間" "責任期間。[使用 start、end 填入起訖時間；尚未結束時不預填實際結束時間。]"
* plan 0..* BackboneElement "照護計畫" "照護計畫。[以下欄位為此項資料的內嵌元素。]"
* plan.status 1..1 code "計畫狀態" "計畫狀態。[填入所綁定值集允許的代碼。]"
* plan.period 0..1 Period "計畫期間" "計畫期間。[使用 start、end 填入起訖時間；尚未結束時不預填實際結束時間。]"
* plan.problem 0..* Reference(HAHCondition) "處理的問題" "處理的問題。[應填入對應的 HAHCondition Reference。]"
* plan.goal 0..* Reference(HAHGoal) "預期目標" "預期目標。[應填入對應的 HAHGoal Reference。]"
* plan.activity 1..* Reference(HAHServiceRequest or HAHMedicationRequest) "預定服務或處方" "預定服務或處方。[應填入對應的 HAHServiceRequest／HAHMedicationRequest Reference。]"
* goal 0..* BackboneElement "照護目標" "照護目標。[以下欄位為此項資料的內嵌元素。]"
* goal.description 1..1 CodeableConcept "預期結果" "預期結果。[描述個案預期達成的結果，不填入疾病或問題清單。]"
* goal.status 1..1 code "目標狀態" "目標狀態。[填入所綁定值集允許的代碼。]"
* goal.due 1..1 date "預期達到日期" "預期達到日期。[填入預期達成目標的日期，使用 YYYY-MM-DD 格式。]"
* goal.result 0..* Reference(Observation) "評值結果" "評值結果。[應填入對應的 Observation Reference。]"
* request 0..* BackboneElement "服務請求" "服務請求。[以下欄位為此項資料的內嵌元素。]"
* request.code 1..1 CodeableConcept "服務項目" "服務項目。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* request.category 1..* CodeableConcept "服務分類" "服務分類。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* request.status 1..1 code "請求狀態" "請求狀態。[填入所綁定值集允許的代碼。]"
* request.intent 1..1 code "請求意圖" "請求意圖。[填入所綁定值集允許的代碼。]"
* request.requester 1..1 Reference(Practitioner or PractitionerRole or Organization) "開立者" "開立者。[應填入對應的 Practitioner／PractitionerRole／Organization Reference。]"
* request.performer 0..* Reference(Practitioner or PractitionerRole or Organization) "執行對象" "執行對象。[應填入對應的 Practitioner／PractitionerRole／Organization Reference。]"
* request.occurrence 0..1 Period "預定服務期間" "預定服務期間。[使用 start、end 填入起訖時間；尚未結束時不預填實際結束時間。]"
* observation 0..* BackboneElement "生命徵象與檢驗" "生命徵象與檢驗。[以下欄位為此項資料的內嵌元素。]"
* observation.code 1..1 CodeableConcept "量測或檢驗項目" "量測或檢驗項目。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* observation.status 1..1 code "結果狀態" "結果狀態。[填入所綁定值集允許的代碼。]"
* observation.time 1..1 dateTime "量測或採檢時間" "量測或採檢時間。[填入實際時間；包含時分時須提供時區。]"
* observation.value 0..1 Quantity "數值與單位" "數值與單位。[填入實際量測數值、UCUM 系統與單位代碼。]"
* observation.textValue 0..1 string "文字結果" "文字結果。[使用文字結果時填寫；不得與數值結果同時填入。]"
* observation.absentReason 0..1 CodeableConcept "缺值原因" "缺值原因。[缺少結果時說明原因，不以零值取代。]"
* observation.component 0..* BackboneElement "同次量測組成值" "同次量測組成值。[血壓等複合量測分別填入各組成結果；單項檢驗不用此欄位。]"
* observation.component.code 1..1 CodeableConcept "組成項目" "組成項目。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* observation.component.value 1..1 Quantity "組成數值" "組成數值。[填入數值、單位及單位代碼系統。]"
* observation.device 0..1 Reference(HAHDevice) "量測設備" "量測設備。[應填入對應的 HAHDevice Reference。]"
* observation.encounter 0..1 Reference(HAHEncounter) "量測對應就診" "量測對應就診。[應填入對應的 HAHEncounter Reference。]"
* observation.specimen 0..1 Reference(Specimen) "檢體" "檢體。[應填入對應的 Specimen Reference。]"
* observation.referenceRange 0..* Range "參考區間" "參考區間。[依此欄位型態填入實際資料。]"
* report 0..* BackboneElement "檢驗報告" "檢驗報告。[以下欄位為此項資料的內嵌元素。]"
* report.identifier 0..* Identifier "報告識別碼" "報告識別碼。[填入識別系統 system 與識別值 value。]"
* report.code 1..1 CodeableConcept "報告種類" "報告種類。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* report.status 1..1 code "報告狀態" "報告狀態。[填入所綁定值集允許的代碼。]"
* report.result 1..* Reference(HAHObservationLab) "單項結果" "單項結果。[應填入對應的 HAHObservationLab Reference。]"
* report.specimen 0..* Reference(Specimen) "檢體" "檢體。[應填入對應的 Specimen Reference。]"
* report.issued 1..1 instant "報告發布時間" "報告發布時間。[依此欄位型態填入實際資料。]"
* medicationOrder 0..* BackboneElement "給藥處方" "給藥處方。[以下欄位為此項資料的內嵌元素。]"
* medicationOrder.medication 1..1 CodeableConcept "藥品" "藥品。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* medicationOrder.status 1..1 code "處方狀態" "處方狀態。[填入所綁定值集允許的代碼。]"
* medicationOrder.intent 1..1 code "處方意圖" "處方意圖。[填入所綁定值集允許的代碼。]"
* medicationOrder.dosage 1..* Dosage "劑量頻率與途徑" "劑量頻率與途徑。[填入用法文字；已知的頻率、途徑、劑量及速率應分別填入 Dosage 子欄位。]"
* medicationOrder.requester 1..1 Reference(Practitioner or PractitionerRole) "開立者" "開立者。[應填入對應的 Practitioner／PractitionerRole Reference。]"
* administration 0..* BackboneElement "實際給藥" "實際給藥。[以下欄位為此項資料的內嵌元素。]"
* administration.request 1..1 Reference(HAHMedicationRequest) "對應處方" "對應處方。[應填入對應的 HAHMedicationRequest Reference。]"
* administration.status 1..1 code "給藥狀態" "給藥狀態。[填入所綁定值集允許的代碼。]"
* administration.reason 0..* CodeableConcept "未給藥或停止原因" "未給藥或停止原因。[未給藥或停止時填入原因。]"
* administration.time 0..1 dateTime "單次給藥時間" "單次給藥時間。[單次給藥填實際時間；持續輸注改填期間。]"
* administration.period 0..1 Period "輸注期間" "輸注期間。[持續輸注填實際起訖期間，不能用排程代替。]"
* administration.dose 0..1 Quantity "給藥劑量" "給藥劑量。[填實際劑量及單位；尚未給藥時不強填零值。]"
* administration.rate 0..1 Quantity "給藥速率" "給藥速率。[填輸注速率與單位，例如 mL/h；不代表處方建議。]"
* administration.route 0..1 CodeableConcept "給藥途徑" "給藥途徑。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* assessment 0..* BackboneElement "臨床評估" "臨床評估。[以下欄位為此項資料的內嵌元素。]"
* assessment.summary 1..1 string "評估摘要" "評估摘要。[以文字記錄整體判斷，並參照相關診斷、檢驗與措施。]"
* assessment.assessor 1..1 Reference(Practitioner or PractitionerRole) "評估人員" "評估人員。[應填入對應的 Practitioner／PractitionerRole Reference。]"
* assessment.time 1..1 dateTime "評估時間" "評估時間。[填入實際時間；包含時分時須提供時區。]"
* assessment.support 0..* Reference(Resource) "支持證據" "支持證據。[應填入對應的 Resource Reference。]"
* procedure 0..* BackboneElement "已執行處置" "已執行處置。[以下欄位為此項資料的內嵌元素。]"
* procedure.code 1..1 CodeableConcept "處置項目" "處置項目。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* procedure.status 1..1 code "處置狀態" "處置狀態。[填入所綁定值集允許的代碼。]"
* procedure.period 0..1 Period "執行期間" "執行期間。[使用 start、end 填入起訖時間；尚未結束時不預填實際結束時間。]"
* procedure.performer 1..* Reference(Practitioner or PractitionerRole) "執行人員" "執行人員。[應填入對應的 Practitioner／PractitionerRole Reference。]"
* procedure.outcome 0..1 CodeableConcept "處置結果" "處置結果。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* allergy 0..* BackboneElement "過敏資訊" "過敏資訊。[以下欄位為此項資料的內嵌元素。]"
* allergy.substance 1..1 CodeableConcept "物質或過敏狀態" "物質或過敏狀態。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* allergy.verification 1..1 CodeableConcept "確認狀態" "確認狀態。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* allergy.manifestation 0..* CodeableConcept "反應表現" "反應表現。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* consent 0..* BackboneElement "照護同意" "照護同意。[以下欄位為此項資料的內嵌元素。]"
* consent.status 1..1 code "同意狀態" "同意狀態。[填入所綁定值集允許的代碼。]"
* consent.scope 1..1 CodeableConcept "同意範圍" "同意範圍。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* consent.source 1..1 Reference(HAHDocumentReference) "來源文件" "來源文件。[參照記錄原始同意文件的 DocumentReference。]"
* communication 0..* BackboneElement "照會與交班" "照會與交班。[以下欄位為此項資料的內嵌元素。]"
* communication.category 1..* CodeableConcept "溝通類型" "溝通類型。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* communication.sender 1..1 Reference(Practitioner or PractitionerRole or Organization or RelatedPerson) "發送者" "發送者。[應填入對應的 Practitioner／PractitionerRole／Organization／RelatedPerson Reference。]"
* communication.recipient 1..* Reference(Resource) "接收者" "接收者。[應填入對應的 Resource Reference。]"
* communication.sent 1..1 dateTime "發送時間" "發送時間。[填入實際時間；包含時分時須提供時區。]"
* communication.content 1..* string "內容" "內容。[填入交班或照會內容；需結構化的診斷及醫囑另建資源。]"
* communication.request 0..* Reference(HAHServiceRequest) "依據請求" "依據請求。[應填入對應的 HAHServiceRequest Reference。]"
* task 0..* BackboneElement "照護工作" "照護工作。[以下欄位為此項資料的內嵌元素。]"
* task.code 1..1 CodeableConcept "工作類型" "工作類型。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* task.status 1..1 code "工作狀態" "工作狀態。[填入所綁定值集允許的代碼。]"
* task.owner 1..1 Reference(Practitioner or PractitionerRole or Organization or CareTeam) "負責人或團隊" "負責人或團隊。[應填入對應的 Practitioner／PractitionerRole／Organization／CareTeam Reference。]"
* task.scheduled 0..1 Period "預定執行期限" "預定執行期限。[填預計執行的時間範圍，不當作已完成紀錄。]"
* task.actual 0..1 Period "實際執行期間" "實際執行期間。[填實際開始與結束時間；已完成工作兩者均須有值。]"
* task.location 0..1 Reference(Location) "工作地點" "工作地點。[應填入對應的 Location Reference。]"
* attachment 0..* BackboneElement "照護附件" "照護附件。[以下欄位為此項資料的內嵌元素。]"
* attachment.type 1..1 CodeableConcept "附件種類" "附件種類。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* attachment.content 1..* Attachment "附件內容或網址" "附件內容或網址。[填 MIME 類型與 base64 內容或可取得的 URL。]"
* attachment.author 1..* Reference(Resource) "作者" "作者。[應填入對應的 Resource Reference。]"
* summary 0..1 BackboneElement "結案與轉銜摘要" "結案與轉銜摘要。[以下欄位為此項資料的內嵌元素。]"
* summary.type 1..1 CodeableConcept "摘要種類" "摘要種類。[已知代碼時填 coding.system 及 coding.code，可用 text 補充說明。]"
* summary.date 1..1 dateTime "文件時間" "文件時間。[填入實際時間；包含時分時須提供時區。]"
* summary.followUp 1..1 string "後續照護與待辦" "後續照護與待辦。[說明接續照護、待辦及尚未知的結果。]"
* summary.documentId 1..1 Identifier "文件識別碼" "文件識別碼。[填唯一的文件識別系統與值；重製文件另給新的識別碼。]"
* intake.decision from HAHEligibilityVS (required)
* episode.outcome from HAHOutcomeVS (required)
* encounter.mode from HAHVisitModeVS (required)
* summary.type from HAHSummaryTypeVS (required)

* patient.gender from http://hl7.org/fhir/ValueSet/administrative-gender (required)
* episode.status from http://hl7.org/fhir/ValueSet/episode-of-care-status (required)
* encounter.status from http://hl7.org/fhir/ValueSet/encounter-status (required)
* goal.status from http://hl7.org/fhir/ValueSet/goal-status (required)
* request.status from http://hl7.org/fhir/ValueSet/request-status (required)
* request.intent from http://hl7.org/fhir/ValueSet/request-intent (required)
* observation.status from http://hl7.org/fhir/ValueSet/observation-status (required)
* report.status from http://hl7.org/fhir/ValueSet/diagnostic-report-status (required)
* medicationOrder.status from http://hl7.org/fhir/ValueSet/medicationrequest-status (required)
* medicationOrder.intent from http://hl7.org/fhir/ValueSet/medicationrequest-intent (required)
* administration.status from http://hl7.org/fhir/ValueSet/medication-admin-status (required)
* procedure.status from http://hl7.org/fhir/ValueSet/event-status (required)
* consent.status from http://hl7.org/fhir/ValueSet/consent-state-codes (required)
* task.status from http://hl7.org/fhir/ValueSet/task-status (required)

Mapping: HAHCareDatasetToFHIR
Id: hah-dataset-fhir
Title: "在宅急症資料集與 FHIR 資源對照"
Source: HAHCareDataset
Target: "http://hl7.org/fhir/R4"
* patient -> "HAHPatient" "來源與差異：patient.js"
* patient.identifier -> "Patient.identifier" "來源與差異：patient.js"
* patient.name -> "Patient.name" "來源與差異：patient.js"
* patient.birthDate -> "Patient.birthDate" "來源與差異：patient.js"
* patient.gender -> "Patient.gender" "來源與差異：patient.js"
* patient.address -> "Patient.address" "來源與差異：patient.js"
* patient.telecom -> "Patient.telecom" "來源與差異：patient.js"
* patient.contact -> "Patient.contact" "來源與差異：patient.js"
* patient.contact.name -> "Patient.contact.name" "來源與差異：patient.js"
* patient.contact.relationship -> "Patient.contact.relationship" "來源與差異：patient.js"
* patient.contact.telecom -> "Patient.contact.telecom" "來源與差異：patient.js"
* patient.caregiver -> "RelatedPerson.patient" "來源與差異：patient.js 的 caregiver；結構化參照為新增"
* patient.deceased -> "Patient.deceasedDateTime" "來源與差異：新增；不可由結案旗標推定"
* intake -> "HAHAssessmentResponse" "來源與差異：新增結構化表單"
* intake.criteria -> "QuestionnaireResponse.item[criteria]" "來源與差異：新增"
* intake.homeSafety -> "QuestionnaireResponse.item[homeSafety]" "來源與差異：新增"
* intake.caregiverSupport -> "QuestionnaireResponse.item[caregiverSupport]" "來源與差異：新增"
* intake.decision -> "QuestionnaireResponse.item[decision]" "來源與差異：新增"
* intake.reason -> "QuestionnaireResponse.item[reason]" "來源與差異：新增"
* intake.assessor -> "QuestionnaireResponse.author" "來源與差異：新增"
* intake.date -> "QuestionnaireResponse.authored" "來源與差異：新增"
* episode -> "HAHEpisodeOfCare" "來源與差異：由 Patient 收案資訊與 Encounter 彙整"
* episode.identifier -> "EpisodeOfCare.identifier" "來源與差異：新增穩定識別"
* episode.status -> "EpisodeOfCare.status" "來源與差異：收案、結案狀態轉換"
* episode.period -> "EpisodeOfCare.period" "來源與差異：收案與結案日期"
* episode.organization -> "EpisodeOfCare.managingOrganization" "來源與差異：patient.js、encounter.js"
* episode.diagnosis -> "EpisodeOfCare.diagnosis.condition" "來源與差異：condition.js"
* episode.team -> "EpisodeOfCare.team" "來源與差異：careTeam.js"
* episode.referral -> "EpisodeOfCare.referralRequest" "來源與差異：新增轉介串聯"
* episode.outcome -> "EpisodeOfCare.extension[outcome]" "來源與差異：EnrollmentInfo.vue；原因代碼需轉換"
* encounter -> "HAHEncounter" "來源與差異：encounter.js"
* encounter.identifier -> "Encounter.identifier" "來源與差異：新增交換識別"
* encounter.status -> "Encounter.status" "來源與差異：encounter.js"
* encounter.class -> "Encounter.class" "來源與差異：IMP、HH；VR 為明確化"
* encounter.period -> "Encounter.period" "來源與差異：encounter.js"
* encounter.parent -> "Encounter.partOf" "來源與差異：新增；單次訪視必填"
* encounter.mode -> "Encounter.extension[mode]" "來源與差異：新增；單次訪視必填"
* encounter.participant -> "Encounter.participant.individual" "來源與差異：encounter.js"
* encounter.organization -> "Encounter.serviceProvider" "來源與差異：encounter.js"
* encounter.location -> "Encounter.location.location" "來源與差異：task.js 的地點與座標"
* encounter.disposition -> "Encounter.hospitalization.dischargeDisposition" "來源與差異：新增結構化資料"
* encounter.destination -> "Encounter.hospitalization.destination" "來源與差異：clinicalNote.js 的 transferHospital"
* problem -> "HAHCondition" "來源與差異：condition.js"
* problem.code -> "Condition.code" "來源與差異：condition.js"
* problem.category -> "Condition.category" "來源與差異：condition.js"
* problem.onset -> "Condition.onsetDateTime" "來源與差異：condition.js"
* problem.clinicalStatus -> "Condition.clinicalStatus" "來源與差異：condition.js"
* problem.verification -> "Condition.verificationStatus" "來源與差異：condition.js"
* problem.encounter -> "Condition.encounter" "來源與差異：condition.js"
* team -> "HAHCareTeam" "來源與差異：careTeam.js"
* team.member -> "CareTeam.participant.member" "來源與差異：careTeam.js"
* team.role -> "CareTeam.participant.role" "來源與差異：careTeam.js"
* team.period -> "CareTeam.participant.period" "來源與差異：新增期間約定"
* plan -> "HAHCarePlan" "來源與差異：goal.js"
* plan.status -> "CarePlan.status" "來源與差異：goal.js"
* plan.period -> "CarePlan.period" "來源與差異：goal.js"
* plan.problem -> "CarePlan.addresses" "來源與差異：需求語意校正"
* plan.goal -> "CarePlan.goal" "來源與差異：goal.js"
* plan.activity -> "CarePlan.activity.reference；也可用 detail" "來源與差異：goal.js 的 activity 結構化"
* goal -> "HAHGoal" "來源與差異：goal.js"
* goal.description -> "Goal.description" "來源與差異：目標與需求分開"
* goal.status -> "Goal.lifecycleStatus" "來源與差異：goal.js"
* goal.due -> "Goal.target.dueDate" "來源與差異：goal.js"
* goal.result -> "Goal.outcomeReference" "來源與差異：新增結果串聯"
* request -> "HAHServiceRequest" "來源與差異：queryNote.js；檢驗及轉介串聯新增"
* request.code -> "ServiceRequest.code" "來源與差異：原本僅部分文字，新增標準化"
* request.category -> "ServiceRequest.category" "來源與差異：新增"
* request.status -> "ServiceRequest.status" "來源與差異：queryNote.js"
* request.intent -> "ServiceRequest.intent" "來源與差異：queryNote.js"
* request.requester -> "ServiceRequest.requester" "來源與差異：queryNote.js"
* request.performer -> "ServiceRequest.performer" "來源與差異：queryNote.js"
* request.occurrence -> "ServiceRequest.occurrencePeriod" "來源與差異：新增"
* observation -> "既有量測 Profiles、HAHObservationLab" "來源與差異：CreateNursingNote.vue、PatientLabReports.vue"
* observation.code -> "Observation.code" "來源與差異：體溫、心率、呼吸、血壓、血氧、血糖、CRP、血氣等"
* observation.status -> "Observation.status" "來源與差異：Observation 寫入流程"
* observation.time -> "Observation.effectiveDateTime" "來源與差異：既有資料"
* observation.value -> "Observation.valueQuantity" "來源與差異：既有數值；須確認 UCUM"
* observation.textValue -> "Observation.valueString" "來源與差異：檢驗頁既有資料"
* observation.absentReason -> "Observation.dataAbsentReason" "來源與差異：新增缺值規則"
* observation.component -> "Observation.component" "來源與差異：血壓專用；單項檢驗不使用"
* observation.component.code -> "Observation.component.code" "來源與差異：收縮壓或舒張壓"
* observation.component.value -> "Observation.component.valueQuantity" "來源與差異：血壓數值與 mm[Hg]"
* observation.device -> "Observation.device" "來源與差異：Device.js"
* observation.encounter -> "Observation.encounter" "來源與差異：修正 focus 作外鍵的用法"
* observation.specimen -> "Observation.specimen" "來源與差異：新增"
* observation.referenceRange -> "Observation.referenceRange.low/high" "來源與差異：PatientLabReports.vue"
* report -> "HAHDiagnosticReport" "來源與差異：新增報告層"
* report.identifier -> "DiagnosticReport.identifier" "來源與差異：新增"
* report.code -> "DiagnosticReport.code" "來源與差異：新增"
* report.status -> "DiagnosticReport.status" "來源與差異：新增"
* report.result -> "DiagnosticReport.result" "來源與差異：連結既有結果"
* report.specimen -> "DiagnosticReport.specimen" "來源與差異：新增"
* report.issued -> "DiagnosticReport.issued" "來源與差異：新增"
* medicationOrder -> "HAHMedicationRequest" "來源與差異：新增；送藥畫面不等於處方"
* medicationOrder.medication -> "MedicationRequest.medicationCodeableConcept 或 medicationReference" "來源與差異：新增"
* medicationOrder.status -> "MedicationRequest.status" "來源與差異：新增"
* medicationOrder.intent -> "MedicationRequest.intent" "來源與差異：新增"
* medicationOrder.dosage -> "MedicationRequest.dosageInstruction" "來源與差異：新增"
* medicationOrder.requester -> "MedicationRequest.requester" "來源與差異：新增"
* administration -> "HAHMedicationAdministration" "來源與差異：新增"
* administration.request -> "MedicationAdministration.request" "來源與差異：新增"
* administration.status -> "MedicationAdministration.status" "來源與差異：新增"
* administration.reason -> "MedicationAdministration.statusReason" "來源與差異：新增"
* administration.time -> "MedicationAdministration.effectiveDateTime" "來源與差異：新增；與期間擇一"
* administration.period -> "MedicationAdministration.effectivePeriod" "來源與差異：新增；與時間點擇一"
* administration.dose -> "MedicationAdministration.dosage.dose" "來源與差異：新增"
* administration.rate -> "MedicationAdministration.dosage.rateQuantity" "來源與差異：新增"
* administration.route -> "MedicationAdministration.dosage.route" "來源與差異：新增"
* assessment -> "HAHClinicalImpression" "來源與差異：clinicalNote.js"
* assessment.summary -> "ClinicalImpression.summary" "來源與差異：原 description、SOAP 文字"
* assessment.assessor -> "ClinicalImpression.assessor" "來源與差異：clinicalNote.js"
* assessment.time -> "ClinicalImpression.effectiveDateTime" "來源與差異：原服務時間"
* assessment.support -> "ClinicalImpression.supportingInfo" "來源與差異：Observation、附件等"
* procedure -> "HAHProcedure" "來源與差異：原護理措施文字；結構化新增"
* procedure.code -> "Procedure.code" "來源與差異：原 selectedInterventions"
* procedure.status -> "Procedure.status" "來源與差異：新增"
* procedure.period -> "Procedure.performedPeriod" "來源與差異：新增；也可用 performedDateTime"
* procedure.performer -> "Procedure.performer.actor" "來源與差異：既有人員"
* procedure.outcome -> "Procedure.outcome" "來源與差異：原評值文字"
* allergy -> "HAHAllergyIntolerance" "來源與差異：原 Condition 過敏旗標不足，新增結構"
* allergy.substance -> "AllergyIntolerance.code" "來源與差異：新增"
* allergy.verification -> "AllergyIntolerance.verificationStatus" "來源與差異：新增"
* allergy.manifestation -> "AllergyIntolerance.reaction.manifestation" "來源與差異：新增"
* consent -> "HAHConsent" "來源與差異：新增"
* consent.status -> "Consent.status" "來源與差異：新增"
* consent.scope -> "Consent.scope" "來源與差異：新增"
* consent.source -> "Consent.sourceReference" "來源與差異：新增；也可用 sourceAttachment"
* communication -> "HAHCommunication" "來源與差異：queryNote.js、handover_notification.py"
* communication.category -> "Communication.category" "來源與差異：新增分類"
* communication.sender -> "Communication.sender" "來源與差異：queryNote.js"
* communication.recipient -> "Communication.recipient" "來源與差異：queryNote.js"
* communication.sent -> "Communication.sent" "來源與差異：queryNote.js"
* communication.content -> "Communication.payload.contentString" "來源與差異：queryNote.js、交班內容"
* communication.request -> "Communication.basedOn" "來源與差異：queryNote.js"
* task -> "HAHVisitTask" "來源與差異：task.js"
* task.code -> "Task.code" "來源與差異：selectedJobs 分類"
* task.status -> "Task.status" "來源與差異：task.js"
* task.owner -> "Task.owner" "來源與差異：task.js"
* task.scheduled -> "Task.restriction.period" "來源與差異：修正原 executionPeriod 語意"
* task.actual -> "Task.executionPeriod" "來源與差異：新增實際起訖"
* task.location -> "Task.location" "來源與差異：task.js"
* attachment -> "HAHDocumentReference" "來源與差異：fhirResources.js"
* attachment.type -> "DocumentReference.type" "來源與差異：既有附件"
* attachment.content -> "DocumentReference.content.attachment" "來源與差異：fhirResources.js"
* attachment.author -> "DocumentReference.author" "來源與差異：fhirResources.js"
* summary -> "HAHCompositionSummary、HAHBundleSummary" "來源與差異：新增文件交換"
* summary.type -> "Composition.type" "來源與差異：新增"
* summary.date -> "Composition.date" "來源與差異：新增"
* summary.followUp -> "Composition.section[followUp].text" "來源與差異：原交班與轉送資料"
* summary.documentId -> "Bundle.identifier" "來源與差異：新增"
